#Import the neccessary Libraries

In [593]:
# Import the necessary libraries
import pandas as pd

# Load the Excel files
kcb = pd.read_excel("/content/QUICK MART 11.6.2025.xlsx")
equity = pd.read_excel("/content/QUICKMART 11062025.xlsx")
aspire = pd.read_csv("/content/ZEDS_CARDS_TILLWISE_2025-06-11.csv")
key = pd.read_excel("/content/card_key.xlsx")

# Display the first few rows of each for verification
print("KCB Data:")
display(kcb.head())

KCB Data:

,MID,Merchant,CURRENCY,Card No,Post Date,Trans Date,NetPaid,Comm,Amount,Auth,RRN,DOCNO,TID
0,14217004,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",404.0,547743******1622,2025-06-11,2025-06-11 15:34:16,425.09,6.91,432.0,724737,1.598402e+09,697240159.0,4C800169
1,14217004,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",404.0,447815******9960,2025-06-11,2025-06-11 15:54:41,1368.74,22.26,1391.0,004480,1.598411e+09,697241766.0,4C801488
2,14217004,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",404.0,418087******9870,2025-06-11,2025-06-11 15:57:05,10353.50,83.50,10437.0,JMVLCR,1.598412e+09,697241895.0,4C800821
3,14217004,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",404.0,426399******2370,2025-06-11,2025-06-11 15:57:15,3616.77,40.23,3657.0,558075,1.598412e+09,697241987.0,4C800169
4,14217004,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",404.0,418087******2328,2025-06-11,2025-06-11 16:12:11,7991.55,64.45,8056.0,JMVNPQ,1.598419e+09,697243395.0,4C800169

In [594]:
print("Equity Data:")
display(equity.head())

Equity Data:

,Merchant_Name,Account_Number,Outlet_Name,Trans_Type,Card_Number,Channel,Purchase,Commission,Cash_Back,Cash_Back_Fee,CashBack_Comm,Trans_Amount,Currency,Mtr_Trans_Amount,Mtr_Trans_Curr,Settlement_Amount,R_R_N,AuthCode,TRANS_DATE,TID,SIC_Code,TRANS_CONDITION,NAME,CONTRACT_NUMBER,BANK_DETAILS
0,QUICK MART LIMITED,310292445852,QUICK MART LAVINGTON TILL 11,Retail,3799 96XX XXX1 686,Our AMEX Cards,3517.46,31.66,0,0,0,3517.46,KES,3517.46,404,3485.80,516213535103,129332,06-11-202519:46:26,649300,5411,POSC,POS Chip PBT Full Grade,068-C-200240,Bank : EQUITY BANK Branch : RUAI BankID : 0006...
1,QUICK MART LIMITED,310292445852,QUICK MART LAVINGTON TILL 11,Retail,4037 45XX XXX0 7653,VISA,4824.80,43.42,0,0,0,4824.80,KES,4824.80,404,4781.38,516213535643,197592,06-11-202519:56:27,649300,5411,POSC,POS Chip PBT Full Grade,068-C-200240,Bank : EQUITY BANK Branch : RUAI BankID : 0006...
2,QUICK MART LIMITED,310292445852,QUICK MART LAVINGTON TILL 11,Retail,4037 45XX XXX6 1142,VISA,370.50,3.33,0,0,0,370.50,KES,370.50,404,367.17,516213536709,198067,06-11-202520:18:46,649300,5411,POSC,POS Chip PBT Full Grade,068-C-200240,Bank : EQUITY BANK Branch : RUAI BankID : 0006...
3,QUICK MART LIMITED,310292445852,QUICK MART LAVINGTON TILL 11,Retail,4225 40XX XXX8 3749,VISA,652.91,5.88,0,0,0,652.91,KES,652.91,404,647.03,516214676646,982288,06-11-202511:28:24,649300,5411,POSC,POS Chip PBT Full Grade,068-C-200240,Bank : EQUITY BANK Branch : RUAI BankID : 0006...
4,QUICK MART LIMITED,310292445852,QUICK MART LAVINGTON TILL 11,Retail,4243 14XX XXX6 8499,Interswitch,9719.06,87.47,0,0,0,9719.06,KES,9719.06,404,9631.59,516314716269,JMXOAH,06-12-202500:06:02,649300,5411,POSC,POS Chip PBT Full Grade,068-C-200240,Bank : EQUITY BANK Branch : RUAI BankID : 0006...

In [595]:
print("Card Key:")
display(key.head())

Card Key:

                         Col_1     Col_2
0  QUICK MART BURUBURU TILL 11  BURUBURU
1    QUICK MART DONHOLM TILL 1     FEDHA
2    QUICK MART DONHOLM TILL 2   DONHOLM
3    QUICK MART DONHOLM TILL 3   DONHOLM
4    QUICK MART DONHOLM TILL 4   DONHOLM

#Bank Cards Statements alignments

##Introduce a column with the bank name

In [596]:
# Step 1: Clean all column names to avoid hidden spaces or newline issues
kcb.columns = kcb.columns.str.strip()
equity.columns = equity.columns.str.strip()

# Step 2: Rename KCB columns to match the target structure
kcb_renamed = kcb.rename(columns={
    'Card No': 'Card_Number',
    'Trans Date': 'TRANS_DATE',
    'RRN': 'R_R_N',
    'Amount': 'Purchase',
    'Comm': 'Commission',
    'NetPaid': 'Settlement_Amount',
    'Merchant': 'store'  # renamed Merchant to store
})

# Step 3: Create Cash_Back and Source columns for KCB
kcb_renamed['Cash_Back'] = kcb_renamed['Purchase'].apply(lambda x: -1 * x if x < 0 else 0)
kcb_renamed['Source'] = 'KCB'

# Step 4: Rename Equity's Outlet_Name to store
equity = equity.rename(columns={'Outlet_Name': 'store'})
equity['Source'] = 'Equity'

# Step 5: Final column list including store
columns = ['TID', 'store', 'Card_Number', 'TRANS_DATE', 'R_R_N',
           'Purchase', 'Commission', 'Settlement_Amount', 'Cash_Back', 'Source']

# Step 6: Align columns and merge
kcb_final = kcb_renamed[columns]
equity_final = equity[columns]
merged_cards = pd.concat([kcb_final, equity_final], ignore_index=True)

# Step 7: Display and save
display(merged_cards.tail())
merged_cards.to_excel("merged_cards.xlsx", index=False)

,TID,store,Card_Number,TRANS_DATE,R_R_N,Purchase,Commission,Settlement_Amount,Cash_Back,Source
5091,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,3567 96XX XXX5 8225,06-11-202515:14:44,5.162147e+11,1999.0,27.99,1971.01,0.0,Equity
5092,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,4407 83XX XXX8 2098,06-11-202520:16:17,5.162147e+11,665.0,5.99,659.01,0.0,Equity
5093,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,4909 05XX XXX8 2152,06-11-202515:15:33,5.162147e+11,450.0,4.05,445.95,0.0,Equity
5094,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,5245 13XX XXX1 4330,06-11-202515:13:16,5.162135e+11,4042.0,48.50,3993.50,0.0,Equity
5095,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,5477 43XX XXX4 8230,06-11-202520:39:28,5.162147e+11,858.0,10.30,847.70,0.0,Equity

##Delete Redundat rows

In [597]:
# Drop rows where Card_Number is NaN or empty string
merged_cards = merged_cards[merged_cards['Card_Number'].notna()]                 # Remove NaN
merged_cards = merged_cards[merged_cards['Card_Number'].astype(str).str.strip() != '']  # Remove blanks

In [598]:
# Count of records by Source
source_counts = merged_cards['Source'].value_counts()

# Display the result
print(source_counts)

Source
Equity    3771
KCB       1269
Name: count, dtype: int64

In [599]:
# Step 1: Load the card_key file
card_key = pd.read_excel("card_key.xlsx", engine="openpyxl")

# Step 2: Clean column names and string values
card_key.columns = card_key.columns.str.strip()
card_key['Col_1'] = card_key['Col_1'].str.strip()
card_key['Col_2'] = card_key['Col_2'].str.strip()
merged_cards['store'] = merged_cards['store'].str.strip()

# Step 3: Create lookup dictionary
lookup_dict = dict(zip(card_key['Col_1'], card_key['Col_2']))

# Step 4: Map and create the 'branch' column
merged_cards['branch'] = merged_cards['store'].map(lookup_dict)

# Step 5: Reorder columns to place 'branch' after 'Source'
cols = list(merged_cards.columns)
source_index = cols.index('Source')
# Move 'branch' to be right after 'Source'
cols.insert(source_index + 1, cols.pop(cols.index('branch')))
merged_cards = merged_cards[cols]

# Step 6: Preview updated data
display(merged_cards.tail())

,TID,store,Card_Number,TRANS_DATE,R_R_N,Purchase,Commission,Settlement_Amount,Cash_Back,Source,branch
5091,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,3567 96XX XXX5 8225,06-11-202515:14:44,5.162147e+11,1999.0,27.99,1971.01,0.0,Equity,HIGHWAY-MLOLONGO
5092,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,4407 83XX XXX8 2098,06-11-202520:16:17,5.162147e+11,665.0,5.99,659.01,0.0,Equity,HIGHWAY-MLOLONGO
5093,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,4909 05XX XXX8 2152,06-11-202515:15:33,5.162147e+11,450.0,4.05,445.95,0.0,Equity,HIGHWAY-MLOLONGO
5094,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,5245 13XX XXX1 4330,06-11-202515:13:16,5.162135e+11,4042.0,48.50,3993.50,0.0,Equity,HIGHWAY-MLOLONGO
5095,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,5477 43XX XXX4 8230,06-11-202520:39:28,5.162147e+11,858.0,10.30,847.70,0.0,Equity,HIGHWAY-MLOLONGO

In [600]:
# Step 1: Ensure Card_Number is a clean string
merged_cards['Card_Number'] = merged_cards['Card_Number'].astype(str).str.strip()

# Step 2: Generate 'card_check' from first 4 + last 4 digits
merged_cards['card_check'] = merged_cards['Card_Number'].apply(
    lambda x: x[:4] + x[-4:] if len(x.replace(" ", "").replace("*", "")) >= 8 else ''
)

# Step 3: Reorder columns to insert 'card_check' right after 'branch'
cols = merged_cards.columns.tolist()
if 'branch' in cols and 'card_check' in cols:
    # Remove 'card_check' temporarily
    cols.remove('card_check')
    # Insert after 'branch'
    branch_index = cols.index('branch')
    cols.insert(branch_index + 1, 'card_check')
    # Apply the new column order
    merged_cards = merged_cards[cols]

# Step 4: Preview the full final table including the new column
display(merged_cards.tail())

,TID,store,Card_Number,TRANS_DATE,R_R_N,Purchase,Commission,Settlement_Amount,Cash_Back,Source,branch,card_check
5091,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,3567 96XX XXX5 8225,06-11-202515:14:44,5.162147e+11,1999.0,27.99,1971.01,0.0,Equity,HIGHWAY-MLOLONGO,35678225
5092,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,4407 83XX XXX8 2098,06-11-202520:16:17,5.162147e+11,665.0,5.99,659.01,0.0,Equity,HIGHWAY-MLOLONGO,44072098
5093,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,4909 05XX XXX8 2152,06-11-202515:15:33,5.162147e+11,450.0,4.05,445.95,0.0,Equity,HIGHWAY-MLOLONGO,49092152
5094,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,5245 13XX XXX1 4330,06-11-202515:13:16,5.162135e+11,4042.0,48.50,3993.50,0.0,Equity,HIGHWAY-MLOLONGO,52454330
5095,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,5477 43XX XXX4 8230,06-11-202520:39:28,5.162147e+11,858.0,10.30,847.70,0.0,Equity,HIGHWAY-MLOLONGO,54778230

In [601]:
print("aspire:")
display(aspire.head())

aspire:

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,AMOUNT,USER_NAME,CARD_TRN_USE_TYPE,HQ_EFT_TRN_NO,BANK_TRN_NO,CUST_CODE,AUTH_CODE,EXP_DATE,TRN_DATE_HOST,REF_NO,RESPONSE_CODE,RESPONSE_TEXT,TERMINAL_ID,TRN_ID,TRN_ID_CRM,RCT_TRN_DATE,Unnamed: 25
0,QM021,FEDHA,2025-06-11 22:33:47.000,5,2873,62,ADANMAUM IBRAHIM,NaN,4478150188599490,851.00,CATHERINE M MUTISYA,PDV,0,024500,NaN,24500,2025-06-11 22:33:47.000,2025-06-11 22:43:33.000,001598583704,0,Operation successfully,4,0,2505028730062,2025-06-12 22:33:47.000,NaN
1,QM012,JIPANGE,2025-06-11 21:42:40.000,6,1941,39,ALICE M,NaN,4407830139281530,138.00,FAITH M KERUBO,PDV,0,881576,NaN,881576,2025-06-11 21:42:39.000,2025-06-11 21:33:42.000,001598573242,0,Operation successfully,41801450,0,1706019410039,2025-06-12 21:42:40.000,NaN
2,QM052,HIGHWAY-MLOLONGO,2025-06-11 22:04:44.000,11,1126,35,NaN,NaN,447815DDDDDD2995,1677.89,JOHN CHEGE MUTHONI,PDI,0,751179,NaN,751179,2029-02-01 00:00:00.000,2025-06-12 00:00:00.000,516214715563,0,Succesfully,403488,1285,1283,2025-06-12 22:04:44.000,NaN
3,QM004,RUAKA,2025-06-11 22:43:31.000,6,4435,53,NaN,NaN,440783DDDDDD3241,596.00,GRACE W KARIMI,PDI,0,474165,NaN,474165,2026-10-01 00:00:00.000,2025-06-12 00:00:00.000,516214715919,0,Succesfully,552894,695,693,2025-06-12 22:43:31.000,NaN
4,QM012,JIPANGE,2025-06-11 23:52:17.000,2,3703,84,NaN,NaN,478393DDDDDD2513,4702.00,NELLY V AYENGO,PDI,0,200881,NaN,200881,2029-05-01 00:00:00.000,2025-06-12 00:00:00.000,516213540308,0,Approved,784750,2320,2323,2025-06-12 23:52:17.000,NaN

In [602]:
# Step 1: Ensure CARD_NUMBER is treated as a clean string
aspire['CARD_NUMBER'] = aspire['CARD_NUMBER'].astype(str).str.strip()

# Step 2: Create the 'card_check' column
aspire['card_check'] = aspire['CARD_NUMBER'].apply(
    lambda x: x[:4] + x[-4:] if len(x.replace(" ", "").replace("*", "")) >= 8 else ''
)

# Step 3: Reorder columns — place 'card_check' at the end (or insert if needed)
# If you want it right after 'CARD_NUMBER', do this:
cols = aspire.columns.tolist()
if 'CARD_NUMBER' in cols and 'card_check' in cols:
    cols.remove('card_check')
    insert_index = cols.index('CARD_NUMBER') + 1
    cols.insert(insert_index, 'card_check')
    aspire = aspire[cols]

# Step 4: Preview full row with new column
display(aspire.head())

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,USER_NAME,CARD_TRN_USE_TYPE,HQ_EFT_TRN_NO,BANK_TRN_NO,CUST_CODE,AUTH_CODE,EXP_DATE,TRN_DATE_HOST,REF_NO,RESPONSE_CODE,RESPONSE_TEXT,TERMINAL_ID,TRN_ID,TRN_ID_CRM,RCT_TRN_DATE,Unnamed: 25
0,QM021,FEDHA,2025-06-11 22:33:47.000,5,2873,62,ADANMAUM IBRAHIM,NaN,4478150188599490,44789490,851.00,CATHERINE M MUTISYA,PDV,0,024500,NaN,24500,2025-06-11 22:33:47.000,2025-06-11 22:43:33.000,001598583704,0,Operation successfully,4,0,2505028730062,2025-06-12 22:33:47.000,NaN
1,QM012,JIPANGE,2025-06-11 21:42:40.000,6,1941,39,ALICE M,NaN,4407830139281530,44071530,138.00,FAITH M KERUBO,PDV,0,881576,NaN,881576,2025-06-11 21:42:39.000,2025-06-11 21:33:42.000,001598573242,0,Operation successfully,41801450,0,1706019410039,2025-06-12 21:42:40.000,NaN
2,QM052,HIGHWAY-MLOLONGO,2025-06-11 22:04:44.000,11,1126,35,NaN,NaN,447815DDDDDD2995,44782995,1677.89,JOHN CHEGE MUTHONI,PDI,0,751179,NaN,751179,2029-02-01 00:00:00.000,2025-06-12 00:00:00.000,516214715563,0,Succesfully,403488,1285,1283,2025-06-12 22:04:44.000,NaN
3,QM004,RUAKA,2025-06-11 22:43:31.000,6,4435,53,NaN,NaN,440783DDDDDD3241,44073241,596.00,GRACE W KARIMI,PDI,0,474165,NaN,474165,2026-10-01 00:00:00.000,2025-06-12 00:00:00.000,516214715919,0,Succesfully,552894,695,693,2025-06-12 22:43:31.000,NaN
4,QM012,JIPANGE,2025-06-11 23:52:17.000,2,3703,84,NaN,NaN,478393DDDDDD2513,47832513,4702.00,NELLY V AYENGO,PDI,0,200881,NaN,200881,2029-05-01 00:00:00.000,2025-06-12 00:00:00.000,516213540308,0,Approved,784750,2320,2323,2025-06-12 23:52:17.000,NaN

In [603]:
aspire.columns.tolist()

['STORE_CODE',
 'STORE_NAME',
 'ZED_DATE',
 'TILL',
 'SESSION',
 'RCT',
 'CUSTOMER_NAME',
 'CARD_TYPE',
 'CARD_NUMBER',
 'card_check',
 'AMOUNT',
 'USER_NAME',
 'CARD_TRN_USE_TYPE',
 'HQ_EFT_TRN_NO',
 'BANK_TRN_NO',
 'CUST_CODE',
 'AUTH_CODE',
 'EXP_DATE',
 'TRN_DATE_HOST',
 'REF_NO',
 'RESPONSE_CODE',
 'RESPONSE_TEXT',
 'TERMINAL_ID',
 'TRN_ID',
 'TRN_ID_CRM',
 'RCT_TRN_DATE',
 'Unnamed: 25']

In [604]:
# Step 1: Filter to required columns
aspire = aspire[[
    'STORE_CODE',
    'STORE_NAME',
    'ZED_DATE',
    'TILL',
    'SESSION',
    'RCT',
    'CUSTOMER_NAME',
    'CARD_TYPE',
    'CARD_NUMBER',
    'card_check',
    'AMOUNT',
    'REF_NO',
    'RCT_TRN_DATE'
]]

# Step 2: Preview
display(aspire.head())

# Step 3: Save to CSV
aspire.to_csv("aspire_filtered.csv", index=False)

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE
0,QM021,FEDHA,2025-06-11 22:33:47.000,5,2873,62,ADANMAUM IBRAHIM,NaN,4478150188599490,44789490,851.00,001598583704,2025-06-12 22:33:47.000
1,QM012,JIPANGE,2025-06-11 21:42:40.000,6,1941,39,ALICE M,NaN,4407830139281530,44071530,138.00,001598573242,2025-06-12 21:42:40.000
2,QM052,HIGHWAY-MLOLONGO,2025-06-11 22:04:44.000,11,1126,35,NaN,NaN,447815DDDDDD2995,44782995,1677.89,516214715563,2025-06-12 22:04:44.000
3,QM004,RUAKA,2025-06-11 22:43:31.000,6,4435,53,NaN,NaN,440783DDDDDD3241,44073241,596.00,516214715919,2025-06-12 22:43:31.000
4,QM012,JIPANGE,2025-06-11 23:52:17.000,2,3703,84,NaN,NaN,478393DDDDDD2513,47832513,4702.00,516213540308,2025-06-12 23:52:17.000

In [605]:
# prompt: rename "REF_NO" column in aspire to "R_R_N"

aspire = aspire.rename(columns={'REF_NO': 'R_R_N'})

# Verify the rename
print("Aspire Data with Renamed Column:")
display(aspire.head())

Aspire Data with Renamed Column:

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,R_R_N,RCT_TRN_DATE
0,QM021,FEDHA,2025-06-11 22:33:47.000,5,2873,62,ADANMAUM IBRAHIM,NaN,4478150188599490,44789490,851.00,001598583704,2025-06-12 22:33:47.000
1,QM012,JIPANGE,2025-06-11 21:42:40.000,6,1941,39,ALICE M,NaN,4407830139281530,44071530,138.00,001598573242,2025-06-12 21:42:40.000
2,QM052,HIGHWAY-MLOLONGO,2025-06-11 22:04:44.000,11,1126,35,NaN,NaN,447815DDDDDD2995,44782995,1677.89,516214715563,2025-06-12 22:04:44.000
3,QM004,RUAKA,2025-06-11 22:43:31.000,6,4435,53,NaN,NaN,440783DDDDDD3241,44073241,596.00,516214715919,2025-06-12 22:43:31.000
4,QM012,JIPANGE,2025-06-11 23:52:17.000,2,3703,84,NaN,NaN,478393DDDDDD2513,47832513,4702.00,516213540308,2025-06-12 23:52:17.000

In [606]:
# Step 1: Ensure R_R_N is string and trimmed in both tables
aspire['R_R_N'] = aspire['R_R_N'].astype(str).str.strip()
merged_cards['R_R_N'] = merged_cards['R_R_N'].astype(str).str.strip()

# Step 2: Merge the tables on the shared column "R_R_N"
rrntable = pd.merge(
    aspire,
    merged_cards,
    on='R_R_N',
    how='inner',  # or 'left'/'outer' depending on what you want to preserve
    suffixes=('_aspire', '_merged')
)

# Step 3: Preview the new table
display(rrntable.head())
print("✅ 'rrntable' created by merging aspire and merged_cards on 'R_R_N'.")

Empty DataFrame
Columns: [STORE_CODE, STORE_NAME, ZED_DATE, TILL, SESSION, RCT, CUSTOMER_NAME, CARD_TYPE, CARD_NUMBER, card_check_aspire, AMOUNT, R_R_N, RCT_TRN_DATE, TID, store, Card_Number, TRANS_DATE, Purchase, Commission, Settlement_Amount, Cash_Back, Source, branch, card_check_merged]
Index: []

✅ 'rrntable' created by merging aspire and merged_cards on 'R_R_N'.

##Align all rows to the branches

In [607]:
# Step 1: Filter rows where 'branch' is missing (NaN or blank)
missing_branch_rows = merged_cards[merged_cards['branch'].isna()]

# Step 2: Count how many rows are missing
missing_count = missing_branch_rows.shape[0]
print(f"✅ Total rows without a branch: {missing_count}")

# Step 3: Display all full unmatched rows
display(missing_branch_rows)

# Step 4: Export full unmatched rows to CSV
missing_branch_rows.to_csv("new_key_full_rows.csv", index=False)
print("✅ Full unmatched rows exported to 'new_key_full_rows.csv'")

✅ Total rows without a branch: 0

Empty DataFrame
Columns: [TID, store, Card_Number, TRANS_DATE, R_R_N, Purchase, Commission, Settlement_Amount, Cash_Back, Source, branch, card_check]
Index: []

✅ Full unmatched rows exported to 'new_key_full_rows.csv'

#Reconcile Aspire and Bank statements

In [608]:
# Step 1: Extract, drop NaNs, get unique and sort alphabetically
card_summary = (
    aspire['STORE_NAME']
    .dropna()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
    .to_frame(name='STORE_NAME')
)

# Step 2: Add index starting from 1
card_summary.index = card_summary.index + 1
card_summary.reset_index(inplace=True)
card_summary.rename(columns={'index': 'No'}, inplace=True)

# Step 3: Save to CSV
card_summary.to_csv("Card_summary.csv", index=False)

# Step 4: Preview
display(card_summary.head())

   No        STORE_NAME
0   1           BANDARI
1   2          BURUBURU
2   3          CHAKA RD
3   4            CHANIA
4   5  CROSSROADS-KAREN

In [609]:
# Step 1: Ensure AMOUNT is numeric (in case there are errors)
aspire['AMOUNT'] = pd.to_numeric(aspire['AMOUNT'], errors='coerce')

# Step 2: Group aspire data to get sum of AMOUNT per STORE_NAME
aspire_sums = aspire.groupby('STORE_NAME')['AMOUNT'].sum().reset_index()

# Step 3: Rename column for clarity
aspire_sums = aspire_sums.rename(columns={'AMOUNT': 'Aspire_Zed'})

# Step 4: Merge with card_summary
card_summary = card_summary.merge(aspire_sums, on='STORE_NAME', how='left')

# Step 5: Fill NaN values (stores with no AMOUNT) with 0
card_summary['Aspire_Zed'] = card_summary['Aspire_Zed'].fillna(0)

# Step 6: Export the updated file
card_summary.to_csv("Card_summary.csv", index=False)

# Step 7: Preview
display(card_summary.head())
print("✅ Updated 'Card_summary.csv' with 'Aspire_Zed' totals.")

   No        STORE_NAME  Aspire_Zed
0   1           BANDARI   184796.51
1   2          BURUBURU   167622.86
2   3          CHAKA RD   237663.93
3   4            CHANIA   337269.39
4   5  CROSSROADS-KAREN   103460.80

✅ Updated 'Card_summary.csv' with 'Aspire_Zed' totals.

In [610]:
# Step 1: Ensure Purchase is numeric
merged_cards['Purchase'] = pd.to_numeric(merged_cards['Purchase'], errors='coerce')

# Step 2: Filter for KCB source and group by branch
kcb_grouped = (
    merged_cards[merged_cards['Source'] == 'KCB']
    .groupby('branch')['Purchase']
    .sum()
    .reset_index()
    .rename(columns={'branch': 'STORE_NAME', 'Purchase': 'kcb_paid'})
)

# Step 3: Merge with card_summary on STORE_NAME
card_summary = card_summary.merge(kcb_grouped, on='STORE_NAME', how='left')

# Step 4: Fill missing values with 0
card_summary['kcb_paid'] = card_summary['kcb_paid'].fillna(0)

# Step 5: Export to CSV
card_summary.to_csv("Card_summary.csv", index=False)

# Step 6: Preview
display(card_summary.tail())
print("✅ 'kcb_paid' column added and Card_summary.csv updated.")

    No       STORE_NAME  Aspire_Zed  kcb_paid
56  57        TOM MBOYA    98801.70  67102.70
57  58  UTAWALA EXPRESS   138961.38  31554.45
58  59     UTAWALA MAIN   131389.36  18024.58
59  60      WAIYAKI WAY   318333.07  54599.60
60  61        WESTLANDS   259006.94  33235.28

✅ 'kcb_paid' column added and Card_summary.csv updated.

In [611]:
# Step 1: Ensure 'Purchase' is numeric
merged_cards['Purchase'] = pd.to_numeric(merged_cards['Purchase'], errors='coerce')

# Step 2: Group Equity values by branch
equity_grouped = (
    merged_cards[merged_cards['Source'] == 'Equity']
    .groupby('branch')['Purchase']
    .sum()
    .reset_index()
    .rename(columns={'branch': 'STORE_NAME', 'Purchase': 'equity_paid'})
)

# Step 3: Merge equity_paid with card_summary
card_summary = card_summary.merge(equity_grouped, on='STORE_NAME', how='left')

# Step 4: Fill missing equity_paid with 0
card_summary['equity_paid'] = card_summary['equity_paid'].fillna(0)

# Step 5: Reorder columns — insert equity_paid right after kcb_paid
cols = list(card_summary.columns)
if 'kcb_paid' in cols and 'equity_paid' in cols:
    kcb_index = cols.index('kcb_paid')
    # Remove equity_paid from current position and re-insert after kcb_paid
    cols.insert(kcb_index + 1, cols.pop(cols.index('equity_paid')))
    card_summary = card_summary[cols]

# Step 6: Add totals row (with comma format)
total_row = pd.DataFrame([{
    'No': '',
    'STORE_NAME': 'TOTAL',
    'Aspire_Zed': card_summary['Aspire_Zed'].sum(),
    'kcb_paid': card_summary['kcb_paid'].sum(),
    'equity_paid': card_summary['equity_paid'].sum()
}])

# Step 7: Match columns and append
for col in card_summary.columns:
    if col not in total_row.columns:
        total_row[col] = ''
total_row = total_row[card_summary.columns]  # Reorder to match
card_summary = pd.concat([card_summary, total_row], ignore_index=True)

# Step 8: Format numeric columns with comma separator
numeric_cols = ['Aspire_Zed', 'kcb_paid', 'equity_paid']
for col in numeric_cols:
    card_summary[col] = card_summary[col].apply(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)

# Step 9: Export final file
card_summary.to_csv("Card_summary.csv", index=False)

# Step 10: Preview
display(card_summary.tail())
print("✅ equity_paid column added, placed after kcb_paid, totals row appended, and numbers formatted with commas.")

    No       STORE_NAME     Aspire_Zed      kcb_paid   equity_paid
57  58  UTAWALA EXPRESS     138,961.38     31,554.45    107,993.93
58  59     UTAWALA MAIN     131,389.36     18,024.58    113,239.78
59  60      WAIYAKI WAY     318,333.07     54,599.60    283,733.47
60  61        WESTLANDS     259,006.94     33,235.28    225,970.66
61                TOTAL  11,640,052.65  3,291,999.79  8,402,623.89

✅ equity_paid column added, placed after kcb_paid, totals row appended, and numbers formatted with commas.

In [612]:
# Step 1: Convert kcb_paid and equity_paid back to numeric (remove commas)
card_summary['kcb_paid'] = card_summary['kcb_paid'].replace({',': ''}, regex=True).astype(float)
card_summary['equity_paid'] = card_summary['equity_paid'].replace({',': ''}, regex=True).astype(float)

# Step 2: Create Gross_Banking
card_summary['Gross_Banking'] = card_summary['kcb_paid'] + card_summary['equity_paid']

# Step 3: Format all numeric columns with commas
numeric_cols = ['Aspire_Zed', 'kcb_paid', 'equity_paid', 'Gross_Banking']
for col in numeric_cols:
    card_summary[col] = card_summary[col].apply(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)

# Step 4: Update totals row
# (Recalculate the actual totals row using numeric versions of the original data)
totals = {
    'No': '',
    'STORE_NAME': 'TOTAL',
    'Aspire_Zed': f"{card_summary[:-1]['Aspire_Zed'].replace({',': ''}, regex=True).astype(float).sum():,.2f}",
    'kcb_paid': f"{card_summary[:-1]['kcb_paid'].replace({',': ''}, regex=True).astype(float).sum():,.2f}",
    'equity_paid': f"{card_summary[:-1]['equity_paid'].replace({',': ''}, regex=True).astype(float).sum():,.2f}",
    'Gross_Banking': f"{card_summary[:-1]['Gross_Banking'].replace({',': ''}, regex=True).astype(float).sum():,.2f}"
}

# Replace the last row (total row) with the updated totals
card_summary.iloc[-1] = totals

# Step 5: Save updated file
card_summary.to_csv("Card_summary.csv", index=False)

# Step 6: Preview
display(card_summary.tail())

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking
57,58,UTAWALA EXPRESS,"138,961.38","31,554.45","107,993.93","139,548.38"
58,59,UTAWALA MAIN,"131,389.36","18,024.58","113,239.78","131,264.36"
59,60,WAIYAKI WAY,"318,333.07","54,599.60","283,733.47","338,333.07"
60,61,WESTLANDS,"259,006.94","33,235.28","225,970.66","259,205.94"
61,,TOTAL,"11,640,052.65","3,291,999.79","8,402,623.89","11,694,623.68"

#Compute Banking Variance

In [613]:
# Load CSV and Excel files
aspire = pd.read_csv('/content/aspire_filtered.csv')
merged_cards = pd.read_excel('/content/merged_cards.xlsx')

# Display first few rows to confirm
aspire.head(), merged_cards.head()

(  STORE_CODE        STORE_NAME                 ZED_DATE  TILL  SESSION  RCT  \
 0      QM021             FEDHA  2025-06-11 22:33:47.000     5     2873   62
 1      QM012           JIPANGE  2025-06-11 21:42:40.000     6     1941   39
 2      QM052  HIGHWAY-MLOLONGO  2025-06-11 22:04:44.000    11     1126   35
 3      QM004             RUAKA  2025-06-11 22:43:31.000     6     4435   53
 4      QM012           JIPANGE  2025-06-11 23:52:17.000     2     3703   84

       CUSTOMER_NAME CARD_TYPE       CARD_NUMBER  card_check   AMOUNT  \
 0  ADANMAUM IBRAHIM       NaN  4478150188599490  44789490.0   851.00
 1           ALICE M       NaN  4407830139281530  44071530.0   138.00
 2               NaN       NaN  447815DDDDDD2995  44782995.0  1677.89
 3               NaN       NaN  440783DDDDDD3241  44073241.0   596.00
 4               NaN       NaN  478393DDDDDD2513  47832513.0  4702.00

          REF_NO             RCT_TRN_DATE
 0  001598583704  2025-06-12 22:33:47.000
 1  001598573242  2025-06-12 21:42:40.000
 2  516214715563  2025-06-12 22:04:44.000
 3  516214715919  2025-06-12 22:43:31.000
 4  516213540308  2025-06-12 23:52:17.000  ,
         TID                                       store       Card_Number  \
 0  4C800169  QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE  547743******1622
 1  4C801488  QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE  447815******9960
 2  4C800821  QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE  418087******9870
 3  4C800169  QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE  426399******2370
 4  4C800169  QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE  418087******2328

             TRANS_DATE         R_R_N  Purchase  Commission  Settlement_Amount  \
 0  2025-06-11 15:34:16  1.598402e+09     432.0        6.91             425.09
 1  2025-06-11 15:54:41  1.598411e+09    1391.0       22.26            1368.74
 2  2025-06-11 15:57:05  1.598412e+09   10437.0       83.50           10353.50
 3  2025-06-11 15:57:15  1.598412e+09    3657.0       40.23            3616.77
 4  2025-06-11 16:12:11  1.598419e+09    8056.0       64.45            7991.55

    Cash_Back Source
 0        0.0    KCB
 1        0.0    KCB
 2        0.0    KCB
 3        0.0    KCB
 4        0.0    KCB  )

In [614]:
# Rename 'R_R_N' in merged_cards to match column in aspire
merged_cards.rename(columns={'R_R_N': 'REF_NO'}, inplace=True)

In [615]:
# Step 3 (Final Fix): Clean REF_NO in merged_cards to string (remove decimals and scientific notation)
def clean_ref_no(x):
    try:
        return str(int(float(x)))  # Works for both float and scientific notation
    except:
        return ""  # If blank or bad format

# Apply safe conversion
merged_cards['REF_NO'] = merged_cards['REF_NO'].apply(clean_ref_no)

# Also make sure aspire REF_NO is string
aspire['REF_NO'] = aspire['REF_NO'].astype(str)

In [616]:
# Clean REF_NO by stripping leading zeros
aspire['REF_NO'] = aspire['REF_NO'].astype(str).str.lstrip('0')

# Create dictionary: REF_NO -> Purchase
ref_to_purchase = dict(zip(merged_cards['REF_NO'], merged_cards['Purchase']))

# Map to rrn_check column
aspire['rrn_check'] = aspire['REF_NO'].map(ref_to_purchase).fillna(0)

In [617]:
# Get all cleaned REF_NO values from aspire
matched_ref_nos = set(aspire['REF_NO'])

# Mark 'Yes' in merged_cards if REF_NO was matched
merged_cards['Cheked_rows'] = merged_cards['REF_NO'].astype(str).apply(lambda x: 'Yes' if x in matched_ref_nos else 'No')

In [618]:
# Count how many rows got a match
matched = (aspire['rrn_check'] > 0).sum()
total = len(aspire)

print(f"✅ Matches found: {matched} out of {total} rows")
print(f"✅ Match percentage: {(matched / total) * 100:.2f}%")
aspire.head()

✅ Matches found: 4894 out of 5024 rows
✅ Match percentage: 97.41%

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check
0,QM021,FEDHA,2025-06-11 22:33:47.000,5,2873,62,ADANMAUM IBRAHIM,NaN,4478150188599490,44789490.0,851.00,1598583704,2025-06-12 22:33:47.000,851.00
1,QM012,JIPANGE,2025-06-11 21:42:40.000,6,1941,39,ALICE M,NaN,4407830139281530,44071530.0,138.00,1598573242,2025-06-12 21:42:40.000,138.00
2,QM052,HIGHWAY-MLOLONGO,2025-06-11 22:04:44.000,11,1126,35,NaN,NaN,447815DDDDDD2995,44782995.0,1677.89,516214715563,2025-06-12 22:04:44.000,1677.89
3,QM004,RUAKA,2025-06-11 22:43:31.000,6,4435,53,NaN,NaN,440783DDDDDD3241,44073241.0,596.00,516214715919,2025-06-12 22:43:31.000,596.00
4,QM012,JIPANGE,2025-06-11 23:52:17.000,2,3703,84,NaN,NaN,478393DDDDDD2513,47832513.0,4702.00,516213540308,2025-06-12 23:52:17.000,4702.00

In [619]:
# Ensure AMOUNT is numeric in case it's not
aspire['AMOUNT'] = pd.to_numeric(aspire['AMOUNT'], errors='coerce')

# Compute val_check as AMOUNT - rrn_check
aspire['val_check'] = aspire['AMOUNT'] - aspire['rrn_check']

# Reorder columns to place 'val_check' after 'rrn_check'
cols = list(aspire.columns)
rrn_idx = cols.index('rrn_check')
# Move val_check to right after rrn_check
new_order = cols[:rrn_idx + 1] + ['val_check'] + cols[rrn_idx + 1:-1] + [cols[-1]]  # keep last column intact
aspire = aspire[new_order]
# Remove duplicate 'val_check' columns if they exist
aspire = aspire.loc[:, ~aspire.columns.duplicated()]


# Preview with all columns
aspire.head()

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check
0,QM021,FEDHA,2025-06-11 22:33:47.000,5,2873,62,ADANMAUM IBRAHIM,NaN,4478150188599490,44789490.0,851.00,1598583704,2025-06-12 22:33:47.000,851.00,0.0
1,QM012,JIPANGE,2025-06-11 21:42:40.000,6,1941,39,ALICE M,NaN,4407830139281530,44071530.0,138.00,1598573242,2025-06-12 21:42:40.000,138.00,0.0
2,QM052,HIGHWAY-MLOLONGO,2025-06-11 22:04:44.000,11,1126,35,NaN,NaN,447815DDDDDD2995,44782995.0,1677.89,516214715563,2025-06-12 22:04:44.000,1677.89,0.0
3,QM004,RUAKA,2025-06-11 22:43:31.000,6,4435,53,NaN,NaN,440783DDDDDD3241,44073241.0,596.00,516214715919,2025-06-12 22:43:31.000,596.00,0.0
4,QM012,JIPANGE,2025-06-11 23:52:17.000,2,3703,84,NaN,NaN,478393DDDDDD2513,47832513.0,4702.00,516213540308,2025-06-12 23:52:17.000,4702.00,0.0

In [620]:

from google.colab import files

# Save the DataFrame to a CSV file
aspire.to_csv("aspire_with_val_check.csv", index=False)

In [621]:
count_rrn_only = (aspire['rrn_check'] > 0).sum()
print(f"✅ rrn_check > 0: {count_rrn_only}")

✅ rrn_check > 0: 4894

In [622]:
# Count rows where val_check is between -3 and 3 (inclusive)
count_val_near_zero = aspire['val_check'].between(-3, 3).sum()

print(f"✅ val_check between -3 and 3: {count_val_near_zero}")

✅ val_check between -3 and 3: 4892

In [623]:
# Count rows where rrn_check > 0 and val_check is between -3 and 3
count_within_range = aspire[(aspire['rrn_check'] > 0) & (aspire['val_check'].between(-3, 3))].shape[0]

print(f"✅ Rows where rrn_check > 0 and val_check is between -3 and 3: {count_within_range}")

✅ Rows where rrn_check > 0 and val_check is between -3 and 3: 4892

In [624]:
# Count mismatched rows where val_check is not between -3 and 3
count_mismatched = aspire[(aspire['rrn_check'] > 0) & (~aspire['val_check'].between(-3, 3))].shape[0]

print(f"❌ Mismatched rows (rrn_check > 0 and val_check NOT between -3 and 3): {count_mismatched}")

❌ Mismatched rows (rrn_check > 0 and val_check NOT between -3 and 3): 2

In [625]:
# Extract rows where rrn_check > 0 and val_check is NOT between -3 and 3
mismatched_rows = aspire[(aspire['rrn_check'] > 0) & (~aspire['val_check'].between(-3, 3))]

# Display top rows
mismatched_rows.head()

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check
3513,QM035,EMBAKASI,2025-06-11 20:36:58.000,2,1825,124,NaN,Visa,4770,NaN,334.0,1598555396,2025-06-11 20:36:58.000,364.00,-30.00
4255,QM022,UTAWALA MAIN,2025-06-11 12:03:18.000,10,1800,7,NaN,NaN,519601DDDDDD0260,51960260.0,125.0,516213502096,2025-06-11 12:03:18.000,1174.15,-1049.15

In [626]:
# Step 1: Ensure Card_Number is string
merged_cards['Card_Number'] = merged_cards['Card_Number'].astype(str)

# Step 2: Create or update 'card_check' column (8 characters only)
merged_cards['card_check'] = merged_cards['Card_Number'].str[:4] + merged_cards['Card_Number'].str[-4:]

# Step 3: Move 'card_check' to appear immediately after 'Source', if Source exists
if 'Source' in merged_cards.columns:
    cols = merged_cards.columns.tolist()
    if 'card_check' in cols:
        cols.remove('card_check')
    source_index = cols.index('Source') + 1
    cols.insert(source_index, 'card_check')
    merged_cards = merged_cards[cols]

# ✅ Step 4: Drop exact duplicate rows
merged_cards = merged_cards.drop_duplicates()

# ✅ Step 5: Exclude rows where "TID" is blank (NaN or empty string)
merged_cards = merged_cards[merged_cards['TID'].notna() & (merged_cards['TID'].astype(str).str.strip() != '')]

# ✅ Step 6: Display result
display(merged_cards.head())

# ✅ Step 7: Download to Excel
merged_cards.to_excel("cleaned_merged_cards.xlsx", index=False)

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows
0,4C800169,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",547743******1622,2025-06-11 15:34:16,1598401749,432.0,6.91,425.09,0.0,KCB,54771622,Yes
1,4C801488,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447815******9960,2025-06-11 15:54:41,1598410960,1391.0,22.26,1368.74,0.0,KCB,44789960,No
2,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",418087******9870,2025-06-11 15:57:05,1598411996,10437.0,83.50,10353.50,0.0,KCB,41809870,No
3,4C800169,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",426399******2370,2025-06-11 15:57:15,1598412068,3657.0,40.23,3616.77,0.0,KCB,42632370,Yes
4,4C800169,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",418087******2328,2025-06-11 16:12:11,1598419285,8056.0,64.45,7991.55,0.0,KCB,41802328,Yes

In [627]:
merged_cards.to_excel("/content/merged_cards.xlsx", index=False)

In [628]:
display(merged_cards.tail())

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows
5091,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,3567 96XX XXX5 8225,06-11-202515:14:44,516214690567,1999.0,27.99,1971.01,0.0,Equity,35678225,Yes
5092,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,4407 83XX XXX8 2098,06-11-202520:16:17,516214712586,665.0,5.99,659.01,0.0,Equity,44072098,Yes
5093,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,4909 05XX XXX8 2152,06-11-202515:15:33,516214690616,450.0,4.05,445.95,0.0,Equity,49092152,Yes
5094,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,5245 13XX XXX1 4330,06-11-202515:13:16,516213514293,4042.0,48.50,3993.50,0.0,Equity,52454330,Yes
5095,276028,QUICKMART MLOLONGO HIGHWAY TILL 9,5477 43XX XXX4 8230,06-11-202520:39:28,516214713555,858.0,10.30,847.70,0.0,Equity,54778230,Yes

In [629]:
# ✅ Step 1: Filter rows where Cheked_rows is "No"
newbankmerged = merged_cards[merged_cards['Cheked_rows'].str.strip().str.upper() == 'NO']

# ✅ Step 2: Display the result
display(newbankmerged.head())

# ✅ Step 3: Optional – Save to Excel
newbankmerged.to_excel("newbankmerged.xlsx", index=False)

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows
1,4C801488,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447815******9960,2025-06-11 15:54:41,1598410960,1391.00,22.26,1368.74,0.0,KCB,44789960,No
2,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",418087******9870,2025-06-11 15:57:05,1598411996,10437.00,83.50,10353.50,0.0,KCB,41809870,No
16,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",429934******4430,2025-06-11 19:17:02,1598528176,1747.00,19.22,1727.78,0.0,KCB,42994430,No
17,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",555458******4386,2025-06-11 19:23:59,1598531047,1741.73,27.87,1713.86,0.0,KCB,55544386,No
19,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447663******0574,2025-06-11 20:04:04,1598545607,96.00,1.06,94.94,0.0,KCB,44760574,No

In [630]:
# Step 1: Ensure both matching columns are string type for consistency
newbankmerged['store'] = newbankmerged['store'].astype(str)
key['Col_1'] = key['Col_1'].astype(str)

# Step 2: Merge key data into newbankmerged based on the 'store' and 'Col_1'
newbankmerged = newbankmerged.merge(
    key[['Col_1', 'Col_2']],
    how='left',
    left_on='store',
    right_on='Col_1'
)

# Step 3: Rename 'Col_2' to 'branch' and drop 'Col_1' (if not needed)
newbankmerged = newbankmerged.rename(columns={'Col_2': 'branch'})
newbankmerged = newbankmerged.drop(columns=['Col_1'])

# Step 4: Display or export result
display(newbankmerged.head())

<ipython-input-630-300702014>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newbankmerged['store'] = newbankmerged['store'].astype(str)

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,branch
0,4C801488,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447815******9960,2025-06-11 15:54:41,1598410960,1391.00,22.26,1368.74,0.0,KCB,44789960,No,RUAKA
1,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",418087******9870,2025-06-11 15:57:05,1598411996,10437.00,83.50,10353.50,0.0,KCB,41809870,No,RUAKA
2,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",429934******4430,2025-06-11 19:17:02,1598528176,1747.00,19.22,1727.78,0.0,KCB,42994430,No,RUAKA
3,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",555458******4386,2025-06-11 19:23:59,1598531047,1741.73,27.87,1713.86,0.0,KCB,55544386,No,RUAKA
4,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447663******0574,2025-06-11 20:04:04,1598545607,96.00,1.06,94.94,0.0,KCB,44760574,No,RUAKA

In [631]:
# ✅ Step 1: Ensure 'branch' and 'Purchase' are strings
newbankmerged['branch'] = newbankmerged['branch'].astype(str)
newbankmerged['Purchase'] = newbankmerged['Purchase'].astype(str)

# ✅ Step 2: Create base 'Check_Two' by combining 'branch' and 'Purchase'
newbankmerged['Check_Two'] = newbankmerged['branch'] + newbankmerged['Purchase']

# ✅ Step 3: Add numeric prefix to distinguish duplicate Check_Two values
newbankmerged['Check_Two'] = (
    newbankmerged.groupby('Check_Two').cumcount() + 1
).astype(str) + newbankmerged['Check_Two']

# ✅ Step 4: Display result
display(newbankmerged.tail(30))

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,branch,Check_Two
120,705360,QUICK MART LTD KISERIAN,4478 15XX XXX7 0737,06-11-202513:56:45,516283132237,609.0,5.48,603.52,0.0,Equity,44780737,No,KISERIAN,1KISERIAN609.0
121,705360,QUICK MART LTD KISERIAN,4478 15XX XXX8 5357,06-11-202516:29:12,516283140089,7572.26,68.15,7504.11,0.0,Equity,44785357,No,KISERIAN,1KISERIAN7572.26
122,705360,QUICK MART LTD KISERIAN,4531 77XX XXX1 5272,06-11-202515:15:45,516283136076,897.0,8.07,888.93,0.0,Equity,45315272,No,KISERIAN,1KISERIAN897.0
123,705360,QUICK MART LTD KISERIAN,4641 47XX XXX2 0123,06-11-202515:38:07,516283137099,5207.0,46.86,5160.14,0.0,Equity,46410123,No,KISERIAN,1KISERIAN5207.0
124,705360,QUICK MART LTD KISERIAN,5477 43XX XXX5 4371,06-11-202518:13:30,516283147667,2291.0,27.49,2263.51,0.0,Equity,54774371,No,KISERIAN,1KISERIAN2291.0
125,705360,QUICK MART LTD KISERIAN,5477 43XX XXX9 0425,06-11-202520:27:48,516283153532,120.0,1.44,118.56,0.0,Equity,54770425,No,KISERIAN,1KISERIAN120.0
126,79766,QUICK MART LTD RUAKA 3,4037 45XX XXX7 5454,06-11-202515:00:09,516282786609,200.0,1.80,198.20,0.0,Equity,40375454,No,RUAKA,1RUAKA200.0
127,79766,QUICK MART LTD RUAKA 3,4037 45XX XXX7 5454,06-11-202514:56:45,516282786446,2647.0,23.82,2623.18,0.0,Equity,40375454,No,RUAKA,1RUAKA2647.0
128,79766,QUICK MART LTD RUAKA 3,4478 15XX XXX6 2195,06-11-202514:49:06,516282786118,4823.0,43.41,4779.59,0.0,Equity,44782195,No,RUAKA,1RUAKA4823.0
129,79766,QUICK MART LTD RUAKA 3,4478 15XX XXX9 0198,06-11-202519:39:37,516282803380,356.0,3.20,352.80,0.0,Equity,44780198,No,RUAKA,1RUAKA356.0
130,746490,QUICK MART MACHAKOS PIONEER 2,4407 83XX XXX3 2091,06-11-202515:32:03,516283136818,1800.0,16.20,1783.80,0.0,Equity,44072091,No,MACHAKOS PIONEER,1MACHAKOS PIONEER1800.0
131,746490,QUICK MART MACHAKOS PIONEER 2,5477 43XX XXX7 3040,06-11-202516:56:12,516282793544,4213.0,50.56,4162.44,0.0,Equity,54773040,No,MACHAKOS PIONEER,1MACHAKOS PIONEER4213.0
132,525698,QUICK MART MACHAKOS PIONEER 3,4531 77XX XXX0 3761,06-11-202517:31:00,516282796015,100.0,0.90,99.10,0.0,Equity,45313761,No,MACHAKOS PIONEER,1MACHAKOS PIONEER100.0
133,525698,QUICK MART MACHAKOS PIONEER 3,4531 77XX XXX0 3761,06-11-202517:31:00,516282796015,100.0,0.90,99.10,0.0,Equity,45313761,No,MACHAKOS PIONEER,2MACHAKOS PIONEER100.0
134,703710,QUICK MART MFANGANO,4407 83XX XXX0 9775,06-11-202519:40:12,516283151992,4126.0,37.13,4088.87,0.0,Equity,44079775,No,MFANGANO,1MFANGANO4126.0
135,703710,QUICK MART MFANGANO,4407 83XX XXX9 6992,06-11-202518:32:38,516282800277,330.0,2.97,327.03,0.0,Equity,44076992,No,MFANGANO,1MFANGANO330.0
136,193790,QUICK MART MFANGANO 1,4478 15XX XXX1 6665,06-11-202506:33:31,516283117587,474.0,4.27,469.73,0.0,Equity,44786665,No,MFANGANO,1MFANGANO474.0
137,193790,QUICK MART MFANGANO 1,4478 15XX XXX4 0043,06-11-202510:44:11,516282773882,120.0,1.08,118.92,0.0,Equity,44780043,No,MFANGANO,1MFANGANO120.0
138,193790,QUICK MART MFANGANO 1,4478 15XX XXX9 2106,06-11-202508:12:49,516283118553,204.0,1.84,202.16,0.0,Equity,44782106,No,MFANGANO,1MFANGANO204.0
139,193790,QUICK MART MFANGANO 1,5196 01XX XXX6 0177,06-11-202511:40:59,516282776448,498.0,4.48,493.52,0.0,Equity,51960177,No,MFANGANO,1MFANGANO498.0
140,880061,QUICK MART NAROK,5467 50XX XXX2 4017,06-11-202513:19:51,516282781366,1919.01,23.03,1895.98,0.0,Equity,54674017,No,NAROK MORAN,1NAROK MORAN1919.01
141,933990,QUICK MART PIPELINE 2,5477 43XX XXX5 2481,06-12-202500:02:56,516314716260,1305.0,15.66,1289.34,0.0,Equity,54772481,No,PIPELINE,1PIPELINE1305.0
142,161698,QUICK MART T MALL 3,4407 83XX XXX6 1607,06-11-202511:08:27,516282774957,886.0,7.97,878.03,0.0,Equity,44071607,No,T-MALL,1T-MALL886.0
143,564570,QUICK MART TOM MBOYA,4243 14XX XXX8 7212,06-11-202521:46:38,516283155308,1806.0,16.25,1789.75,0.0,Equity,42437212,No,TOM MBOYA,1TOM MBOYA1806.0
144,564570,QUICK MART TOM MBOYA,4478 15XX XXX3 0394,06-11-202521:07:58,516283154558,1420.0,12.78,1407.22,0.0,Equity,44780394,No,TOM MBOYA,1TOM MBOYA1420.0
145,647709,QUICK MART WESTLANDS 4,3799 96XX XXX8 209,06-11-202518:49:48,516214706910,1858.0,16.72,1841.28,0.0,Equity,3799 209,No,WESTLANDS,1WESTLANDS1858.0
146,647709,QUICK MART WESTLANDS 4,4407 83XX XXX7 5598,06-11-202520:48:15,516213537872,145.0,1.31,143.69,0.0,Equity,44075598,No,WESTLANDS,1WESTLANDS145.0
147,647709,QUICK MART WESTLANDS 4,4407 83XX XXX9 1517,06-11-202513:38:57,516214684876,279.75,2.52,277.23,0.0,Equity,44071517,No,WESTLANDS,1WESTLANDS279.75
148,114397,QUICK MART WESTLANDS TILL 1,4407 83XX XXX9 0224,06-12-202500:04:15,516313540343,199.0,1.79,197.21,0.0,Equity,44070224,No,WESTLANDS,1WESTLANDS199.0
149,576653,QUICKMART MLOLONGO HIGHWAY 2,4407 83XX XXX9 9432,06-11-202519:55:58,516283152564,2109.2,18.98,2090.22,0.0,Equity,44079432,No,HIGHWAY-MLOLONGO,1HIGHWAY-MLOLONGO2109.2

In [632]:
# ✅ Step: Create 'Check_Two' with 2 decimal places while keeping all original columns
newbankmerged['Check_Two'] = (
    newbankmerged['branch'].astype(str).str.strip().str.upper() +
    newbankmerged['Purchase'].astype(float).map('{:.2f}'.format)
)
# ✅ Step 2: Add numeric prefix to distinguish duplicate Check_Two values
newbankmerged['Check_Two'] = (
    newbankmerged.groupby('Check_Two').cumcount() + 1
).astype(str) + newbankmerged['Check_Two']

# ✅ Display all columns (first few rows)
display(newbankmerged.head(40))

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,branch,Check_Two
0,4C801488,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447815******9960,2025-06-11 15:54:41,1598410960,1391.0,22.26,1368.74,0.0,KCB,44789960,No,RUAKA,1RUAKA1391.00
1,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",418087******9870,2025-06-11 15:57:05,1598411996,10437.0,83.50,10353.50,0.0,KCB,41809870,No,RUAKA,1RUAKA10437.00
2,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",429934******4430,2025-06-11 19:17:02,1598528176,1747.0,19.22,1727.78,0.0,KCB,42994430,No,RUAKA,1RUAKA1747.00
3,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",555458******4386,2025-06-11 19:23:59,1598531047,1741.73,27.87,1713.86,0.0,KCB,55544386,No,RUAKA,1RUAKA1741.73
4,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447663******0574,2025-06-11 20:04:04,1598545607,96.0,1.06,94.94,0.0,KCB,44760574,No,RUAKA,1RUAKA96.00
5,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",464160******6102,2025-06-11 21:24:00,1598568375,3687.75,40.57,3647.18,0.0,KCB,46416102,No,RUAKA,1RUAKA3687.75
6,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",440783******6406,2025-06-11 21:44:22,1598573613,1937.0,21.31,1915.69,0.0,KCB,44076406,No,RUAKA,1RUAKA1937.00
7,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",440783******1812,2025-06-11 22:15:50,1598580312,1031.0,11.34,1019.66,0.0,KCB,44071812,No,RUAKA,1RUAKA1031.00
8,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",440783******3457,2025-06-11 19:56:04,1598542924,1506.0,16.57,1489.43,0.0,KCB,44073457,No,RUAKA,1RUAKA1506.00
9,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",425199******7119,2025-06-11 21:15:48,1598566385,664.0,7.30,656.70,0.0,KCB,42517119,No,RUAKA,1RUAKA664.00
10,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",464160******6480,2025-06-11 21:39:07,1598572259,2244.0,24.68,2219.32,0.0,KCB,46416480,No,RUAKA,1RUAKA2244.00
11,38810330,"QUICK MART RUIRU,NEAR MIXMAX TRADE CENTRE,RUIR...",519601******7168,2025-06-11 08:15:10,1598218699,2053.0,32.85,2020.15,0.0,KCB,51967168,No,RUIRU,1RUIRU2053.00
12,R4812083,"QUICK MART WAIYAKI WAY,LAVINGTON,RUIRU,KE",418087******9355,2025-06-11 15:18:54,1598395152,20000.0,160.00,19840.00,0.0,KCB,41809355,No,WAIYAKI WAY,1WAIYAKI WAY20000.00
13,4C801470,"QUICK MART JIPANGE,THIKA ROAD MALL,RUIRU,KE",517094******2859,2025-06-11 09:48:35,1598249176,1228.0,19.65,1208.35,0.0,KCB,51702859,No,JIPANGE,1JIPANGE1228.00
14,4C801470,"QUICK MART JIPANGE,THIKA ROAD MALL,RUIRU,KE",429934******8032,2025-06-11 09:54:22,1598251301,780.0,8.58,771.42,0.0,KCB,42998032,No,JIPANGE,1JIPANGE780.00
15,4C801470,"QUICK MART JIPANGE,THIKA ROAD MALL,RUIRU,KE",489001******6527,2025-06-11 14:55:34,1598385229,1302.0,14.32,1287.68,0.0,KCB,48906527,No,JIPANGE,1JIPANGE1302.00
16,4C801470,"QUICK MART JIPANGE,THIKA ROAD MALL,RUIRU,KE",447815******8080,2025-06-11 14:59:15,1598386835,156.0,2.50,153.50,0.0,KCB,44788080,No,JIPANGE,1JIPANGE156.00
17,R8810399,"QUICK MART DONHOLM,DONHOLM,RUIRU,KE",440783******1871,2025-06-11 14:19:09,1598370157,536.0,5.90,530.10,0.0,KCB,44071871,No,DONHOLM,1DONHOLM536.00
18,R8810399,"QUICK MART DONHOLM,DONHOLM,RUIRU,KE",453177******8497,2025-06-11 17:09:13,1598454927,1196.0,13.16,1182.84,0.0,KCB,45318497,No,DONHOLM,1DONHOLM1196.00
19,41801772,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",557084******2317,NaN,1595250769,1805.0,28.88,1776.12,0.0,KCB,55702317,No,RONGAI EXPRESS,1RONGAI EXPRESS1805.00
20,4C800824,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",454681******1142,2025-06-11 17:26:30,1598466307,756.0,8.32,747.68,0.0,KCB,45461142,No,RONGAI EXPRESS,1RONGAI EXPRESS756.00
21,4C800824,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",454681******1142,2025-06-11 17:29:12,1598466307,-756.0,-8.32,-747.68,756.0,KCB,45461142,No,RONGAI EXPRESS,1RONGAI EXPRESS-756.00
22,34812220,"QUICK MART NYALENDA,NYALENDA,RUIRU,KE",462821******7311,2025-06-11 18:54:58,1598518503,7189.46,79.08,7110.38,0.0,KCB,46287311,No,NYALENDA,1NYALENDA7189.46
23,2A204490,"QUICK MART TOM MBOYA,BURUBURU,RUIRU,KE",418087******8521,2025-06-11 08:25:04,1598221331,11500.0,92.00,11408.00,0.0,KCB,41808521,No,TOM MBOYA,1TOM MBOYA11500.00
24,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",418087******2748,2025-06-11 16:52:00,1598444005,190.0,1.52,188.48,0.0,KCB,41802748,No,EASTERN BYPASS 2,1EASTERN BYPASS 2190.00
25,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",519601******6783,2025-06-11 17:25:56,1598465853,1997.75,31.96,1965.79,0.0,KCB,51966783,No,EASTERN BYPASS 2,1EASTERN BYPASS 21997.75
26,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",523523******7890,2025-06-11 17:43:33,1598477683,1723.0,27.57,1695.43,0.0,KCB,52357890,No,EASTERN BYPASS 2,1EASTERN BYPASS 21723.00
27,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",447663******1814,2025-06-11 17:54:02,1598484453,1115.0,12.27,1102.73,0.0,KCB,44761814,No,EASTERN BYPASS 2,1EASTERN BYPASS 21115.00
28,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",447815******7423,2025-06-11 17:35:08,1598472007,6401.0,102.42,6298.58,0.0,KCB,44787423,No,EASTERN BYPASS 2,1EASTERN BYPASS 26401.00
29,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",424314******5707,2025-06-11 17:50:06,1598481863,484.18,3.87,480.31,0.0,KCB,42435707,No,EASTERN BYPASS 2,1EASTERN BYPASS 2484.18
30,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",422540******8927,2025-06-11 18:58:12,1598520017,608.0,6.69,601.31,0.0,KCB,42258927,No,EASTERN BYPASS 2,1EASTERN BYPASS 2608.00
31,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",417482******4017,2025-06-11 19:26:50,1598532084,1258.0,10.06,1247.94,0.0,KCB,41744017,No,EASTERN BYPASS 2,1EASTERN BYPASS 21258.00
32,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",447815******4799,2025-06-11 19:32:28,1598534152,1749.0,27.98,1721.02,0.0,KCB,44784799,No,EASTERN BYPASS 2,1EASTERN BYPASS 21749.00
33,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",523523******2235,2025-06-11 21:07:33,1598564273,1495.0,23.92,1471.08,0.0,KCB,52352235,No,EASTERN BYPASS 2,1EASTERN BYPASS 21495.00
34,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",447663******3364,2025-06-11 18:03:39,1598490615,1210.0,13.31,1196.69,0.0,KCB,44763364,No,EASTERN BYPASS 2,1EASTERN BYPASS 21210.00
35,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",424314******9552,2025-06-11 19:03:38,1598522508,671.0,5.37,665.63,0.0,KCB,42439552,No,EASTERN BYPASS 2,1EASTERN BYPASS 2671.00
36,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",453177******3788,2025-06-11 19:41:42,1598537774,152.54,1.68,150.86,0.0,KCB,45313788,No,EASTERN BYPASS 2,1EASTERN BYPASS 2152.54
37,38812885,"QUICK MART EASTERNBYPASS 2,NEAR MIXMAX TRADE C...",519601******9243,2025-06-11 20:11:33,1598548096,4215.0,67.44,4147.56,0.0,KCB,51969243,No,EASTERN BYPASS 2,1EASTERN BYPASS 24215.00
38,4C800221,"QUICK MART EMBAKASI,QUICK MART EMBAKASI,RUIRU,KE",424314******2054,2025-06-11 17:50:22,1598482007,5610.0,44.88,5565.12,0.0,KCB,42432054,No,EMBAKASI,1EMBAKASI5610.00
39,4C800221,"QUICK MART EMBAKASI,QUICK MART EMBAKASI,RUIRU,KE",453177******1397,2025-06-11 17:41:47,1598476453,700.0,7.70,692.30,0.0,KCB,45311397,No,EMBAKASI,1EMBAKASI700.00

In [633]:
# Step 1: Load the card_key file
card_key = pd.read_excel('/content/card_key.xlsx')

# Step 2: Ensure matching key columns are strings
merged_cards['store'] = merged_cards['store'].astype(str)
card_key.iloc[:, 0] = card_key.iloc[:, 0].astype(str)

# Step 3: Create a lookup dictionary: store -> branch (2nd column)
store_to_branch = dict(zip(card_key.iloc[:, 0], card_key.iloc[:, 1]))

# Step 4: Map branch to merged_cards using the store column
merged_cards['branch'] = merged_cards['store'].map(store_to_branch)

# Step 5: Move 'branch' column to appear right after 'store'
cols = merged_cards.columns.tolist()
cols.remove('branch')
store_index = cols.index('store') + 1
cols.insert(store_index, 'branch')
merged_cards = merged_cards[cols]

# Step 6: Preview updated DataFrame
display(merged_cards.head())

,TID,store,branch,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows
0,4C800169,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",RUAKA,547743******1622,2025-06-11 15:34:16,1598401749,432.0,6.91,425.09,0.0,KCB,54771622,Yes
1,4C801488,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",RUAKA,447815******9960,2025-06-11 15:54:41,1598410960,1391.0,22.26,1368.74,0.0,KCB,44789960,No
2,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",RUAKA,418087******9870,2025-06-11 15:57:05,1598411996,10437.0,83.50,10353.50,0.0,KCB,41809870,No
3,4C800169,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",RUAKA,426399******2370,2025-06-11 15:57:15,1598412068,3657.0,40.23,3616.77,0.0,KCB,42632370,Yes
4,4C800169,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",RUAKA,418087******2328,2025-06-11 16:12:11,1598419285,8056.0,64.45,7991.55,0.0,KCB,41802328,Yes

In [634]:
aspire.tail()

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check
5019,QM054,T-MALL,2025-06-11 19:40:46.000,7,1137,140,NaN,NaN,462063DDDDDD3064,46203064.0,7538.35,516213534769,2025-06-11 19:40:46.000,7538.35,0.0
5020,QM054,T-MALL,2025-06-11 20:09:29.000,8,1138,155,NaN,NaN,523523DDDDDD6053,52356053.0,1570.78,516214712229,2025-06-11 20:09:29.000,1570.78,0.0
5021,QM054,T-MALL,2025-06-11 18:15:26.000,13,1046,112,NaN,NaN,424314DDDDDD4514,42434514.0,6600.00,516213528049,2025-06-11 18:15:26.000,6600.00,0.0
5022,QM055,MILELE-NGONG,2025-06-11 10:42:59.000,4,1252,83,ALICE M,NaN,4478150150055133,44785133.0,783.00,1598271277,2025-06-11 10:42:59.000,783.00,0.0
5023,QM055,MILELE-NGONG,2025-06-11 10:56:56.000,4,1252,92,ANTONY SYENGO,NaN,5196010161067709,51967709.0,445.00,1598278500,2025-06-11 10:56:56.000,445.00,0.0

In [635]:
# Count where rrn_check > 1
greater_than_1 = (aspire['rrn_check'] > 1).sum()

# Count where rrn_check <= 0
zero_or_below = (aspire['rrn_check'] <= 0).sum()

# Print results
print(f"🔹 Transactions with rrn_check > 1: {greater_than_1}")
print(f"🔸 Transactions with rrn_check <= 0: {zero_or_below}")

🔹 Transactions with rrn_check > 1: 4894
🔸 Transactions with rrn_check <= 0: 130

In [636]:
# ✅ Filter rows where 'rrn_check' is less than or equal to 0
newaspire = aspire[aspire['rrn_check'] <= 0].copy()

# ✅ Preview the result
display(newaspire.tail())

# ✅ Optional: Confirm row count
print(f"Total rows in newaspire (rrn_check <= 0): {len(newaspire)}")

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check
4769,QM014,EASTERN BYPASS 2,2025-06-11 17:52:26.000,5,2046,72,NaN,Visa,5707,NaN,484.18,1863,2025-06-11 17:52:26.000,0.0,484.18
4770,QM014,EASTERN BYPASS 2,2025-06-11 20:12:19.000,5,2046,136,NaN,Visa,9243,NaN,4215.00,8096,2025-06-11 20:12:19.000,0.0,4215.00
4792,QM014,EASTERN BYPASS 2,2025-06-11 17:26:16.000,5,2046,59,NaN,Visa,6783,NaN,1997.75,5853,2025-06-11 17:26:16.000,0.0,1997.75
4793,QM014,EASTERN BYPASS 2,2025-06-11 19:27:19.000,5,2046,112,NaN,Visa,4017,NaN,1258.00,2084,2025-06-11 19:27:19.000,0.0,1258.00
4807,QM030,TOM MBOYA,2025-06-11 21:52:09.000,3,3300,89,NaN,Visa,4314,NaN,1806.00,7212,2025-06-11 21:52:09.000,0.0,1806.00

Total rows in newaspire (rrn_check <= 0): 130

In [637]:
# 1. Count total rows
row_count = len(newaspire)
print(f"📊 Total rows in newaspire: {row_count}")

# 2. View column names and data types
print("\n🧾 Column Info:")
print(newaspire.dtypes)

# 3. Summary statistics for numeric columns
print("\n📈 Summary Stats:")
display(newaspire.describe(include='all'))

# 4. Check for missing values per column
print("\n🔍 Missing Values:")
print(newaspire.isnull().sum())

# 5. Preview first few rows
print("\n🗂️ Sample Rows:")
display(newaspire.head())

📊 Total rows in newaspire: 130

🧾 Column Info:
STORE_CODE        object
STORE_NAME        object
ZED_DATE          object
TILL               int64
SESSION            int64
RCT                int64
CUSTOMER_NAME     object
CARD_TYPE         object
CARD_NUMBER       object
card_check       float64
AMOUNT           float64
REF_NO            object
RCT_TRN_DATE      object
rrn_check        float64
val_check        float64
dtype: object

📈 Summary Stats:

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check
count,130,130,130,130.000000,130.000000,130.000000,0,124,130,8.000000e+00,130.000000,130,130,130.0,130.000000
unique,30,30,130,NaN,NaN,NaN,0,2,124,NaN,NaN,126,130,NaN,NaN
top,QM004,RUAKA,2025-06-11 22:57:52.000,NaN,NaN,NaN,NaN,Visa,2112,NaN,NaN,15,2025-06-12 22:57:52.000,NaN,NaN
freq,21,21,1,NaN,NaN,NaN,NaN,123,2,NaN,NaN,3,1,NaN,NaN
mean,NaN,NaN,NaN,5.323077,2099.530769,105.615385,NaN,NaN,NaN,5.108078e+07,2279.551692,NaN,NaN,0.0,2279.551692
std,NaN,NaN,NaN,3.009585,1125.525505,70.949309,NaN,NaN,NaN,7.923926e+06,2626.772538,NaN,NaN,0.0,2626.772538
min,NaN,NaN,NaN,1.000000,96.000000,1.000000,NaN,NaN,NaN,4.243092e+07,45.000000,NaN,NaN,0.0,45.000000
25%,NaN,NaN,NaN,3.000000,1432.000000,56.500000,NaN,NaN,NaN,4.477978e+07,507.500000,NaN,NaN,0.0,507.500000
50%,NaN,NaN,NaN,5.000000,1922.000000,100.000000,NaN,NaN,NaN,4.973181e+07,1341.100000,NaN,NaN,0.0,1341.100000
75%,NaN,NaN,NaN,7.000000,2894.750000,151.000000,NaN,NaN,NaN,5.441790e+07,2641.500000,NaN,NaN,0.0,2641.500000
max,NaN,NaN,NaN,14.000000,4439.000000,369.000000,NaN,NaN,NaN,6.278731e+07,13725.200000,NaN,NaN,0.0,13725.200000

🔍 Missing Values:
STORE_CODE         0
STORE_NAME         0
ZED_DATE           0
TILL               0
SESSION            0
RCT                0
CUSTOMER_NAME    130
CARD_TYPE          6
CARD_NUMBER        0
card_check       122
AMOUNT             0
REF_NO             0
RCT_TRN_DATE       0
rrn_check          0
val_check          0
dtype: int64

🗂️ Sample Rows:

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check
6,QM043,OTC,2025-06-11 22:57:52.000,8,2450,84,NaN,Visa,4362,NaN,1054.0,7729,2025-06-12 22:57:52.000,0.0,1054.0
15,QM006,KIAMBU RD,2025-06-11 21:54:59.000,3,3993,29,NaN,NaN,627851DDDDDD7310,62787310.0,45.0,516214715422,2025-06-12 21:54:59.000,0.0,45.0
23,QM004,RUAKA,2025-06-11 23:08:45.000,7,4439,66,NaN,Visa,2112,NaN,605.0,6251,2025-06-12 23:08:45.000,0.0,605.0
43,QM004,RUAKA,2025-06-11 23:03:32.000,7,4439,62,NaN,Visa,2112,NaN,890.0,7611,2025-06-12 23:03:32.000,0.0,890.0
83,QM004,RUAKA,2025-06-11 21:28:21.000,7,4439,1,NaN,Visa,7631,NaN,2532.0,4979,2025-06-12 21:28:21.000,0.0,2532.0

In [638]:
# ✅ Step 1: Ensure 'STORE_NAME' is string and format 'AMOUNT' to 2 decimal places
newaspire['Check_Two'] = newaspire['STORE_NAME'].astype(str) + newaspire['AMOUNT'].map('{:.2f}'.format)

# ✅ Step 2: Add numeric prefix to distinguish duplicate Check_Two values
newaspire['Check_Two'] = (
    newaspire.groupby('Check_Two').cumcount() + 1
).astype(str) + newaspire['Check_Two']

# ✅ Step 3: Preview the result
display(newaspire.head())

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check,Check_Two
6,QM043,OTC,2025-06-11 22:57:52.000,8,2450,84,NaN,Visa,4362,NaN,1054.0,7729,2025-06-12 22:57:52.000,0.0,1054.0,1OTC1054.00
15,QM006,KIAMBU RD,2025-06-11 21:54:59.000,3,3993,29,NaN,NaN,627851DDDDDD7310,62787310.0,45.0,516214715422,2025-06-12 21:54:59.000,0.0,45.0,1KIAMBU RD45.00
23,QM004,RUAKA,2025-06-11 23:08:45.000,7,4439,66,NaN,Visa,2112,NaN,605.0,6251,2025-06-12 23:08:45.000,0.0,605.0,1RUAKA605.00
43,QM004,RUAKA,2025-06-11 23:03:32.000,7,4439,62,NaN,Visa,2112,NaN,890.0,7611,2025-06-12 23:03:32.000,0.0,890.0,1RUAKA890.00
83,QM004,RUAKA,2025-06-11 21:28:21.000,7,4439,1,NaN,Visa,7631,NaN,2532.0,4979,2025-06-12 21:28:21.000,0.0,2532.0,1RUAKA2532.00

In [639]:
# Step 1: Standardize Check_Two in both datasets
newaspire['Check_Two'] = newaspire['STORE_NAME'].astype(str).str.strip().str.upper() + \
                         newaspire['AMOUNT'].astype(float).astype(int).astype(str)

newbankmerged['Check_Two'] = newbankmerged['branch'].astype(str).str.strip().str.upper() + \
                             newbankmerged['Purchase'].astype(float).astype(int).astype(str)

# Step 2: Create a copy of newbankmerged Check_Two values as a "pool" of available matches
available_matches = newbankmerged['Check_Two'].tolist()

# Step 3: Define a function that consumes matches once
def check_and_consume(val):
    if val in available_matches:
        available_matches.remove(val)
        return 'Okay'
    else:
        return 'False'

# Step 4: Apply function row-by-row
newaspire['Amount_check'] = newaspire['Check_Two'].apply(check_and_consume)

# Step 5: Count and preview
okay_count = (newaspire['Amount_check'] == 'Okay').sum()
print(f"✅ Unique matches marked as 'Okay': {okay_count}")

# ✅ Step 2: Add numeric prefix to distinguish duplicate Check_Two values
newaspire['Check_Two'] = (
    newaspire.groupby('Check_Two').cumcount() + 1
).astype(str) + newaspire['Check_Two']
display(newaspire.tail())

✅ Unique matches marked as 'Okay': 122

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check,Check_Two,Amount_check
4769,QM014,EASTERN BYPASS 2,2025-06-11 17:52:26.000,5,2046,72,NaN,Visa,5707,NaN,484.18,1863,2025-06-11 17:52:26.000,0.0,484.18,1EASTERN BYPASS 2484,Okay
4770,QM014,EASTERN BYPASS 2,2025-06-11 20:12:19.000,5,2046,136,NaN,Visa,9243,NaN,4215.00,8096,2025-06-11 20:12:19.000,0.0,4215.00,1EASTERN BYPASS 24215,Okay
4792,QM014,EASTERN BYPASS 2,2025-06-11 17:26:16.000,5,2046,59,NaN,Visa,6783,NaN,1997.75,5853,2025-06-11 17:26:16.000,0.0,1997.75,1EASTERN BYPASS 21997,Okay
4793,QM014,EASTERN BYPASS 2,2025-06-11 19:27:19.000,5,2046,112,NaN,Visa,4017,NaN,1258.00,2084,2025-06-11 19:27:19.000,0.0,1258.00,1EASTERN BYPASS 21258,Okay
4807,QM030,TOM MBOYA,2025-06-11 21:52:09.000,3,3300,89,NaN,Visa,4314,NaN,1806.00,7212,2025-06-11 21:52:09.000,0.0,1806.00,1TOM MBOYA1806,Okay

In [640]:
okay_count = (newaspire['Amount_check'] == 'Okay').sum()
false_count = (newaspire['Amount_check'] == 'False').sum()
total = len(newaspire)

print(f"✅ Unique matches marked as 'Okay': {okay_count}")
print(f"❌ Transactions without match (False): {false_count}")
print(f"📊 Total transactions checked: {total}")

✅ Unique matches marked as 'Okay': 122
❌ Transactions without match (False): 8
📊 Total transactions checked: 130

In [641]:
# Filter where Amount_check is 'False'
false_list = newaspire[newaspire['Amount_check'] == 'False'].copy()

# ✅ Step 2: Add numeric prefix to distinguish duplicate Check_Two values
newaspire['Check_Two'] = (
    newaspire.groupby('Check_Two').cumcount() + 1
).astype(str) + newaspire['Check_Two']

# Display the list
display(false_list)

# Optional: Show count
print(f"❌ Total unmatched (False) transactions: {len(false_list)}")

,STORE_CODE,STORE_NAME,ZED_DATE,TILL,SESSION,RCT,CUSTOMER_NAME,CARD_TYPE,CARD_NUMBER,card_check,AMOUNT,REF_NO,RCT_TRN_DATE,rrn_check,val_check,Check_Two,Amount_check
15,QM006,KIAMBU RD,2025-06-11 21:54:59.000,3,3993,29,NaN,NaN,627851DDDDDD7310,62787310.0,45.0,516214715422,2025-06-12 21:54:59.000,0.0,45.0,1KIAMBU RD45,False
449,QM056,CROSSROADS-KAREN,2025-06-11 17:54:17.000,4,1088,152,NaN,NaN,478394DDDDDD7174,47837174.0,3869.0,516213526199,2025-06-11 17:54:17.000,0.0,3869.0,1CROSSROADS-KAREN3869,False
553,QM056,CROSSROADS-KAREN,2025-06-11 14:27:58.000,5,1244,246,NaN,NaN,424314DDDDDD0915,42430915.0,172.0,516213511493,2025-06-11 14:27:58.000,0.0,172.0,1CROSSROADS-KAREN172,False
781,QM044,MTWAPA MALL,2025-06-11 17:47:11.000,11,1102,18,NaN,Visa,4338,NaN,4989.0,515513137310,2025-06-11 17:47:11.000,0.0,4989.0,1MTWAPA MALL4989,False
882,QM032,MFANGANO,2025-06-11 17:18:13.000,5,2105,122,NaN,Visa,2007,NaN,160.0,516283143459,2025-06-11 17:18:12.000,0.0,160.0,1MFANGANO160,False
2150,QM004,RUAKA,2025-06-11 00:02:09.000,8,4431,111,NaN,NaN,447663DDDDDD5270,44765270.0,1763.0,516213487348,2025-06-11 00:02:09.000,0.0,1763.0,1RUAKA1763,False
2172,QM005,KAHAWA SUKARI,2025-06-11 00:11:25.000,3,3803,110,NaN,NaN,627851DDDDDD5955,62785955.0,652.0,516214663879,2025-06-11 00:11:25.000,0.0,652.0,1KAHAWA SUKARI652,False
2187,QM004,RUAKA,2025-06-11 00:04:11.000,8,4431,112,NaN,NaN,447815DDDDDD4622,44784622.0,599.0,516213487358,2025-06-11 00:04:11.000,0.0,599.0,1RUAKA599,False

❌ Total unmatched (False) transactions: 8

In [642]:
# ✅ Step 2: Add numeric prefix to distinguish duplicate Check_Two values
newbankmerged['Check_Two'] = (
    newbankmerged.groupby('Check_Two').cumcount() + 1
).astype(str) + newbankmerged['Check_Two']
display(newbankmerged.tail())

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,branch,Check_Two
145,647709,QUICK MART WESTLANDS 4,3799 96XX XXX8 209,06-11-202518:49:48,516214706910,1858.0,16.72,1841.28,0.0,Equity,3799 209,No,WESTLANDS,1WESTLANDS1858
146,647709,QUICK MART WESTLANDS 4,4407 83XX XXX7 5598,06-11-202520:48:15,516213537872,145.0,1.31,143.69,0.0,Equity,44075598,No,WESTLANDS,1WESTLANDS145
147,647709,QUICK MART WESTLANDS 4,4407 83XX XXX9 1517,06-11-202513:38:57,516214684876,279.75,2.52,277.23,0.0,Equity,44071517,No,WESTLANDS,1WESTLANDS279
148,114397,QUICK MART WESTLANDS TILL 1,4407 83XX XXX9 0224,06-12-202500:04:15,516313540343,199.0,1.79,197.21,0.0,Equity,44070224,No,WESTLANDS,1WESTLANDS199
149,576653,QUICKMART MLOLONGO HIGHWAY 2,4407 83XX XXX9 9432,06-11-202519:55:58,516283152564,2109.2,18.98,2090.22,0.0,Equity,44079432,No,HIGHWAY-MLOLONGO,1HIGHWAY-MLOLONGO2109

In [643]:
# prompt: display(newbankmerged.head()

display(newbankmerged.head())

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,branch,Check_Two
0,4C801488,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447815******9960,2025-06-11 15:54:41,1598410960,1391.0,22.26,1368.74,0.0,KCB,44789960,No,RUAKA,1RUAKA1391
1,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",418087******9870,2025-06-11 15:57:05,1598411996,10437.0,83.50,10353.50,0.0,KCB,41809870,No,RUAKA,1RUAKA10437
2,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",429934******4430,2025-06-11 19:17:02,1598528176,1747.0,19.22,1727.78,0.0,KCB,42994430,No,RUAKA,1RUAKA1747
3,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",555458******4386,2025-06-11 19:23:59,1598531047,1741.73,27.87,1713.86,0.0,KCB,55544386,No,RUAKA,1RUAKA1741
4,4C800821,"QUICK MART LTD RUAKA,LIMURU ROAD,NAKURU,KE",447663******0574,2025-06-11 20:04:04,1598545607,96.0,1.06,94.94,0.0,KCB,44760574,No,RUAKA,1RUAKA96

In [644]:
# ✅ Step 1: Create a fresh pool of available Check_Two values from newaspire
aspire_available_matches = newaspire['Check_Two'].tolist()

# ✅ Step 2: Define function that consumes match from aspire pool
def check_and_consume_from_aspire(val):
    if val in aspire_available_matches:
        aspire_available_matches.remove(val)
        return 'Okay'
    else:
        return 'False'

# ✅ Step 3: Apply to newbankmerged
newbankmerged['Amount_check'] = newbankmerged['Check_Two'].apply(check_and_consume_from_aspire)

# ✅ Step 4: Count and preview
okay_count_bank = (newbankmerged['Amount_check'] == 'Okay').sum()
print(f"✅ Unique matches marked as 'Okay' in newbankmerged: {okay_count_bank}")
display(newbankmerged.tail())

✅ Unique matches marked as 'Okay' in newbankmerged: 0

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,branch,Check_Two,Amount_check
145,647709,QUICK MART WESTLANDS 4,3799 96XX XXX8 209,06-11-202518:49:48,516214706910,1858.0,16.72,1841.28,0.0,Equity,3799 209,No,WESTLANDS,1WESTLANDS1858,False
146,647709,QUICK MART WESTLANDS 4,4407 83XX XXX7 5598,06-11-202520:48:15,516213537872,145.0,1.31,143.69,0.0,Equity,44075598,No,WESTLANDS,1WESTLANDS145,False
147,647709,QUICK MART WESTLANDS 4,4407 83XX XXX9 1517,06-11-202513:38:57,516214684876,279.75,2.52,277.23,0.0,Equity,44071517,No,WESTLANDS,1WESTLANDS279,False
148,114397,QUICK MART WESTLANDS TILL 1,4407 83XX XXX9 0224,06-12-202500:04:15,516313540343,199.0,1.79,197.21,0.0,Equity,44070224,No,WESTLANDS,1WESTLANDS199,False
149,576653,QUICKMART MLOLONGO HIGHWAY 2,4407 83XX XXX9 9432,06-11-202519:55:58,516283152564,2109.2,18.98,2090.22,0.0,Equity,44079432,No,HIGHWAY-MLOLONGO,1HIGHWAY-MLOLONGO2109,False

In [645]:
import pandas as pd

# ✅ Step 1: Define newmerged_cards if not already defined, and filter Cheked_rows = 'No' & Amount_check = 'False'
if 'newmerged_cards' not in locals():
    newmerged_cards = newbankmerged[
        (newbankmerged['Cheked_rows'].str.strip().str.lower() == 'no') &
        (newbankmerged['Amount_check'].astype(str).str.strip().str.lower() == 'false')
    ].copy()

# ✅ Step 2: Save to Excel
filename = "newmerged_cards.xlsx"
newmerged_cards.to_excel(filename, index=False)

# ✅ Step 3: Provide download link (Colab only)
from IPython.display import FileLink, display
display(FileLink(filename))

/content/newmerged_cards.xlsx

In [646]:
# ✅ Step 1: Standardize Check_Two in both datasets
newaspire['Check_Two'] = (
    newaspire['STORE_NAME'].astype(str)
    .str.replace(r'\s+', '', regex=True)
    .str.upper() +
    newaspire['AMOUNT'].astype(float).round().astype(int).astype(str)
)

newmerged_cards['Check_Two'] = (
    newmerged_cards['branch'].astype(str)
    .str.replace(r'\s+', '', regex=True)
    .str.upper() +
    newmerged_cards['Purchase'].astype(float).round().astype(int).astype(str)
)

# ✅ Step 2: Filter newmerged_cards to only rows that have potential matches
valid_check_twos = set(newaspire['Check_Two'])
newmerged_cards['Matchable'] = newmerged_cards['Check_Two'].isin(valid_check_twos)

# ✅ Step 3: Create a pool to consume from
available_aspire_matches = newaspire['Check_Two'].tolist()

# ✅ Step 4: Match-and-consume only for valid rows
def match_and_consume(val):
    if val in available_aspire_matches:
        available_aspire_matches.remove(val)
        return 'Okay'
    return 'False'

# ✅ Step 5: Apply match logic only where Matchable is True
newmerged_cards['Amount_check'] = 'False'
newmerged_cards.loc[newmerged_cards['Matchable'], 'Amount_check'] = newmerged_cards.loc[
    newmerged_cards['Matchable'], 'Check_Two'
].apply(match_and_consume)

# ✅ Step 2: Add numeric prefix to distinguish duplicate Check_Two values
newmerged_cards['Check_Two'] = (
    newmerged_cards.groupby('Check_Two').cumcount() + 1
).astype(str) + newmerged_cards['Check_Two']

# ✅ Step 6: Preview results
okay_count = (newmerged_cards['Amount_check'] == 'Okay').sum()
print(f"✅ Unique matches found from newaspire: {okay_count}")
display(newmerged_cards.head())

✅ Unique matches found from newaspire: 0

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,Check_Two,Amount_check,Matchable,branch
0,R4812083,"QUICK MART WAIYAKI WAY,LAVINGTON,RUIRU,KE",418087******9355,2025-06-11 15:18:54,1598395152,20000.0,160.00,19840.00,0.0,KCB,41809355,No,1WAIYAKIWAY20000,False,False,WAIYAKI WAY
1,41801772,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",557084******2317,NaN,1595250769,1805.0,28.88,1776.12,0.0,KCB,55702317,No,1RONGAIEXPRESS1805,False,False,RONGAI EXPRESS
2,4C800824,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",454681******1142,2025-06-11 17:26:30,1598466307,756.0,8.32,747.68,0.0,KCB,45461142,No,1RONGAIEXPRESS756,False,False,RONGAI EXPRESS
3,4C800824,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",454681******1142,2025-06-11 17:29:12,1598466307,-756.0,-8.32,-747.68,756.0,KCB,45461142,No,1RONGAIEXPRESS-756,False,False,RONGAI EXPRESS
4,2A204490,"QUICK MART TOM MBOYA,BURUBURU,RUIRU,KE",418087******8521,2025-06-11 08:25:04,1598221331,11500.0,92.00,11408.00,0.0,KCB,41808521,No,1TOMMBOYA11500,False,False,TOM MBOYA

In [647]:
# ✅ Step 1: Standardize 'store' and 'Col_1' columns for case-insensitive matching
newmerged_cards['store'] = newmerged_cards['store'].astype(str).str.strip().str.upper()
card_key['Col_1'] = card_key['Col_1'].astype(str).str.strip().str.upper()

# ✅ Step 2: Drop old 'branch' column if it exists
newmerged_cards.drop(columns=['branch'], errors='ignore', inplace=True)

# ✅ Step 3: Merge full card_key data into full newmerged_cards
newmerged_cards = newmerged_cards.merge(
    card_key[['Col_1', 'Col_2']],
    how='left',
    left_on='store',
    right_on='Col_1'
)

# ✅ Step 4: Rename merged column to 'branch' and clean up
newmerged_cards.rename(columns={'Col_2': 'branch'}, inplace=True)
newmerged_cards.drop(columns=['Col_1'], inplace=True)

# ✅ Step 2: Add numeric prefix to distinguish duplicate Check_Two values
newmerged_cards['Check_Two'] = (
    newmerged_cards.groupby('Check_Two').cumcount() + 1
).astype(str) + newmerged_cards['Check_Two']

# ✅ Step 5: Display full updated table with all original + new columns
pd.set_option('display.max_columns', None)  # show all columns
display(newmerged_cards.head())  # shows all columns now including 'branch'

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,Check_Two,Amount_check,Matchable,branch
0,R4812083,"QUICK MART WAIYAKI WAY,LAVINGTON,RUIRU,KE",418087******9355,2025-06-11 15:18:54,1598395152,20000.0,160.00,19840.00,0.0,KCB,41809355,No,11WAIYAKIWAY20000,False,False,WAIYAKI WAY
1,41801772,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",557084******2317,NaN,1595250769,1805.0,28.88,1776.12,0.0,KCB,55702317,No,11RONGAIEXPRESS1805,False,False,RONGAI EXPRESS
2,4C800824,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",454681******1142,2025-06-11 17:26:30,1598466307,756.0,8.32,747.68,0.0,KCB,45461142,No,11RONGAIEXPRESS756,False,False,RONGAI EXPRESS
3,4C800824,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",454681******1142,2025-06-11 17:29:12,1598466307,-756.0,-8.32,-747.68,756.0,KCB,45461142,No,11RONGAIEXPRESS-756,False,False,RONGAI EXPRESS
4,2A204490,"QUICK MART TOM MBOYA,BURUBURU,RUIRU,KE",418087******8521,2025-06-11 08:25:04,1598221331,11500.0,92.00,11408.00,0.0,KCB,41808521,No,11TOMMBOYA11500,False,False,TOM MBOYA

In [648]:
newmerged_cards = newmerged_cards[newmerged_cards['Matchable'] != True]

In [649]:
display(newmerged_cards.head())

,TID,store,Card_Number,TRANS_DATE,REF_NO,Purchase,Commission,Settlement_Amount,Cash_Back,Source,card_check,Cheked_rows,Check_Two,Amount_check,Matchable,branch
0,R4812083,"QUICK MART WAIYAKI WAY,LAVINGTON,RUIRU,KE",418087******9355,2025-06-11 15:18:54,1598395152,20000.0,160.00,19840.00,0.0,KCB,41809355,No,11WAIYAKIWAY20000,False,False,WAIYAKI WAY
1,41801772,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",557084******2317,NaN,1595250769,1805.0,28.88,1776.12,0.0,KCB,55702317,No,11RONGAIEXPRESS1805,False,False,RONGAI EXPRESS
2,4C800824,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",454681******1142,2025-06-11 17:26:30,1598466307,756.0,8.32,747.68,0.0,KCB,45461142,No,11RONGAIEXPRESS756,False,False,RONGAI EXPRESS
3,4C800824,"QUICK MART RONGAI EXPRESS,RONGAI EXPRESS,NAIRO...",454681******1142,2025-06-11 17:29:12,1598466307,-756.0,-8.32,-747.68,756.0,KCB,45461142,No,11RONGAIEXPRESS-756,False,False,RONGAI EXPRESS
4,2A204490,"QUICK MART TOM MBOYA,BURUBURU,RUIRU,KE",418087******8521,2025-06-11 08:25:04,1598221331,11500.0,92.00,11408.00,0.0,KCB,41808521,No,11TOMMBOYA11500,False,False,TOM MBOYA

In [650]:
import pandas as pd

# ✅ Step 1: Standardize Check_Two values (remove spaces and uppercase)
newaspire['Check_Two'] = (
    newaspire['STORE_NAME'].astype(str).str.replace(r'\s+', '', regex=True).str.upper() +
    newaspire['AMOUNT'].astype(float).astype(int).astype(str)
)

newmerged_cards['Check_Two'] = (
    newmerged_cards['branch'].astype(str).str.replace(r'\s+', '', regex=True).str.upper() +
    newmerged_cards['Purchase'].astype(float).astype(int).astype(str)
)

# ✅ Step 2: Create a pool from newaspire for matching and tracking
available_aspire_pool = newaspire.set_index('Check_Two').to_dict('index')  # traceable match pool
match_trace = {}  # store what matched

# ✅ Step 3: Define match function that logs the matched row
def match_and_trace(val):
    if val in available_aspire_pool:
        match_trace[val] = available_aspire_pool.pop(val)  # trace and consume
        return 'Okay'
    return 'False'

# ✅ Step 4: Apply function to newmerged_cards
newmerged_cards['Amount_check'] = newmerged_cards['Check_Two'].apply(match_and_trace)

In [651]:
match_trace.get('JOSKA4553', '❌ No match found')

'❌ No match found'

In [652]:
'OUTERING6013' in newaspire['Check_Two'].values

False

In [653]:
# Count summary of Amount_check
summary_counts = newmerged_cards['Amount_check'].value_counts()

# Print total count and breakdown
print(f"📊 Total rows in newmerged_cards: {len(newmerged_cards)}")
print("✅ Amount_check summary:")
print(summary_counts)

📊 Total rows in newmerged_cards: 26
✅ Amount_check summary:
Amount_check
False    25
Okay      1
Name: count, dtype: int64

In [654]:
display(card_summary.tail())

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking
57,58,UTAWALA EXPRESS,"138,961.38","31,554.45","107,993.93","139,548.38"
58,59,UTAWALA MAIN,"131,389.36","18,024.58","113,239.78","131,264.36"
59,60,WAIYAKI WAY,"318,333.07","54,599.60","283,733.47","338,333.07"
60,61,WESTLANDS,"259,006.94","33,235.28","225,970.66","259,205.94"
61,,TOTAL,"11,640,052.65","3,291,999.79","8,402,623.89","11,694,623.68"

In [655]:
# Step 1: List numeric columns to clean
numeric_cols = ['Aspire_Zed', 'kcb_paid', 'equity_paid', 'Gross_Banking']

# Step 2: Convert all numeric columns to float after removing commas
for col in numeric_cols:
    card_summary[col] = card_summary[col].replace(',', '', regex=True).astype(float)

# Step 3: Compute Variance
card_summary['Variance'] = card_summary['Gross_Banking'] - card_summary['Aspire_Zed']

# Step 4: Remove old TOTAL row if it exists
card_summary = card_summary[card_summary['STORE_NAME'] != 'TOTAL']

# Step 5: Compute fresh totals
totals = card_summary[numeric_cols + ['Variance']].sum()
total_row = pd.DataFrame([{
    'No': '',
    'STORE_NAME': 'TOTAL',
    'Aspire_Zed': totals['Aspire_Zed'],
    'kcb_paid': totals['kcb_paid'],
    'equity_paid': totals['equity_paid'],
    'Gross_Banking': totals['Gross_Banking'],
    'Variance': totals['Variance']
}])

# Step 6: Append the clean total row
card_summary = pd.concat([card_summary, total_row], ignore_index=True)

# Step 7: Display
display(card_summary.tail())

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking,Variance
57,58,UTAWALA EXPRESS,138961.38,31554.45,107993.93,139548.38,587.00
58,59,UTAWALA MAIN,131389.36,18024.58,113239.78,131264.36,-125.00
59,60,WAIYAKI WAY,318333.07,54599.60,283733.47,338333.07,20000.00
60,61,WESTLANDS,259006.94,33235.28,225970.66,259205.94,199.00
61,,TOTAL,11640052.65,3291999.79,8402623.89,11694623.68,54571.03

In [656]:
# ✅ Step 1: Filter relevant KCB unmatched records
kcb_recs_data = newmerged_cards[
    (newmerged_cards['Source'].str.upper() == 'KCB') &
    (newmerged_cards['Amount_check'].astype(str).str.strip().str.lower() == 'false')
]

# ✅ Step 2: Ensure 'Purchase' is numeric
kcb_recs_data['Purchase'] = pd.to_numeric(kcb_recs_data['Purchase'], errors='coerce')

# ✅ Drop rows where Purchase is NaN (can't sum invalids)
kcb_recs_data = kcb_recs_data.dropna(subset=['Purchase'])

# ✅ Step 3: Group by branch and sum Purchase
kcb_recs_grouped = kcb_recs_data.groupby('branch')['Purchase'].sum().reset_index()
kcb_recs_grouped.columns = ['STORE_NAME', 'kcb_recs']

# ✅ Step 4: Drop existing kcb_recs if present
if 'kcb_recs' in card_summary.columns:
    card_summary.drop(columns=['kcb_recs'], inplace=True)

# ✅ Step 5: Merge with card_summary
card_summary = card_summary.merge(kcb_recs_grouped, on='STORE_NAME', how='left')
card_summary['kcb_recs'] = card_summary['kcb_recs'].fillna(0)

# ✅ Step 6: Remove old TOTAL row
card_summary = card_summary[card_summary['STORE_NAME'] != 'TOTAL']

# ✅ Step 7: Ensure numeric columns are properly typed
numeric_cols = ['Aspire_Zed', 'kcb_paid', 'equity_paid', 'Gross_Banking', 'Variance', 'kcb_recs']
card_summary[numeric_cols] = card_summary[numeric_cols].apply(pd.to_numeric, errors='coerce')

# ✅ Step 8: Compute totals
totals = card_summary[numeric_cols].sum()

# ✅ Step 9: Build TOTAL row
total_row = pd.DataFrame([{
    'No': '',
    'STORE_NAME': 'TOTAL',
    'Aspire_Zed': totals['Aspire_Zed'],
    'kcb_paid': totals['kcb_paid'],
    'equity_paid': totals['equity_paid'],
    'Gross_Banking': totals['Gross_Banking'],
    'Variance': totals['Variance'],
    'kcb_recs': totals['kcb_recs']
}])

# ✅ Step 10: Append TOTAL row
card_summary = pd.concat([card_summary, total_row], ignore_index=True)

# ✅ Step 11: Display final result
display(card_summary.head(10))

<ipython-input-656-1078966712>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kcb_recs_data['Purchase'] = pd.to_numeric(kcb_recs_data['Purchase'], errors='coerce')

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking,Variance,kcb_recs
0,1,BANDARI,184796.51,18492.01,171304.50,189796.51,5000.00,5000.0
1,2,BURUBURU,167622.86,0.00,167622.86,167622.86,0.00,0.0
2,3,CHAKA RD,237663.93,146374.84,95205.54,241580.38,3916.45,0.0
3,4,CHANIA,337269.39,80762.36,256507.03,337269.39,0.00,0.0
4,5,CROSSROADS-KAREN,103460.80,0.00,100360.80,100360.80,-3100.00,0.0
5,6,DONHOLM,111860.50,56317.05,55543.45,111860.50,0.00,0.0
6,7,EASTERN BYPASS 1,160548.77,124415.44,36847.33,161262.77,714.00,0.0
7,8,EASTERN BYPASS 2,193582.67,28021.47,165561.20,193582.67,0.00,0.0
8,9,ELDOCENTER,96255.78,14339.05,81916.73,96255.78,0.00,0.0
9,10,EMBAKASI,381095.77,105676.68,275449.09,381125.77,30.00,0.0

In [657]:
# ✅ PRE-FIX: Ensure equity_recs_data is defined from the source DataFrame
# Assuming 'newmerged_cards' is the source and 'EQUITY' is the relevant value in the 'Source' column
equity_recs_data = newmerged_cards[
    (newmerged_cards['Source'].str.upper() == 'EQUITY') &
    (newmerged_cards['Amount_check'] == 'False')
].copy()

# ✅ Step 1: Ensure Purchase column is numeric
equity_recs_data['Purchase'] = pd.to_numeric(equity_recs_data['Purchase'], errors='coerce')

# ✅ Step 2: Drop any rows with NaN in Purchase
equity_recs_data = equity_recs_data.dropna(subset=['Purchase'])

# ✅ Step 3: Group by branch and sum Purchase
equity_recs_grouped = equity_recs_data.groupby('branch')['Purchase'].sum().reset_index()
equity_recs_grouped.columns = ['STORE_NAME', 'Equity_recs']

# ✅ Step 4: Drop old Equity_recs if exists
if 'Equity_recs' in card_summary.columns:
    card_summary.drop(columns=['Equity_recs'], inplace=True)

# ✅ Step 5: Merge into card_summary
card_summary = card_summary.merge(equity_recs_grouped, on='STORE_NAME', how='left')
card_summary['Equity_recs'] = card_summary['Equity_recs'].fillna(0)

# ✅ Step 6: Remove old TOTAL row
card_summary = card_summary[card_summary['STORE_NAME'] != 'TOTAL']

# ✅ Step 7: Define all numeric columns
numeric_cols = ['Aspire_Zed', 'kcb_paid', 'equity_paid', 'Gross_Banking',
                'Variance', 'kcb_recs', 'Equity_recs']

# ✅ Step 8: Convert all numeric columns to numeric types
card_summary[numeric_cols] = card_summary[numeric_cols].apply(pd.to_numeric, errors='coerce')

# ✅ Step 9: Compute totals
totals = card_summary[numeric_cols].sum()

# ✅ Step 10: Build TOTAL row
total_row = pd.DataFrame([{
    'No': '',
    'STORE_NAME': 'TOTAL',
    'Aspire_Zed': totals['Aspire_Zed'],
    'kcb_paid': totals['kcb_paid'],
    'equity_paid': totals['equity_paid'],
    'Gross_Banking': totals['Gross_Banking'],
    'Variance': totals['Variance'],
    'kcb_recs': totals['kcb_recs'],
    'Equity_recs': totals['Equity_recs']
}])

# ✅ Step 11: Append TOTAL row
card_summary = pd.concat([card_summary, total_row], ignore_index=True)

# ✅ Step 12: Display result
display(card_summary.head(19))

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking,Variance,kcb_recs,Equity_recs
0,1,BANDARI,184796.51,18492.01,171304.50,189796.51,5000.00,5000.0,0.00
1,2,BURUBURU,167622.86,0.00,167622.86,167622.86,0.00,0.0,0.00
2,3,CHAKA RD,237663.93,146374.84,95205.54,241580.38,3916.45,0.0,3916.45
3,4,CHANIA,337269.39,80762.36,256507.03,337269.39,0.00,0.0,0.00
4,5,CROSSROADS-KAREN,103460.80,0.00,100360.80,100360.80,-3100.00,0.0,941.00
5,6,DONHOLM,111860.50,56317.05,55543.45,111860.50,0.00,0.0,0.00
6,7,EASTERN BYPASS 1,160548.77,124415.44,36847.33,161262.77,714.00,0.0,714.00
7,8,EASTERN BYPASS 2,193582.67,28021.47,165561.20,193582.67,0.00,0.0,0.00
8,9,ELDOCENTER,96255.78,14339.05,81916.73,96255.78,0.00,0.0,0.00
9,10,EMBAKASI,381095.77,105676.68,275449.09,381125.77,30.00,0.0,0.00
10,11,FEDHA,256301.37,33586.25,222715.12,256301.37,0.00,0.0,0.00
11,12,HIGHWAY-MLOLONGO,111618.44,12805.15,99552.29,112357.44,739.00,739.0,0.00
12,13,JIPANGE,312616.38,94592.06,218024.32,312616.38,0.00,0.0,0.00
13,14,JOSKA,167188.39,129020.37,38168.02,167188.39,0.00,0.0,0.00
14,15,KAHAWA SUKARI,97730.52,36872.97,60205.55,97078.52,-652.00,0.0,0.00
15,16,KAHAWA WEST,214501.11,141162.37,73338.74,214501.11,0.00,0.0,0.00
16,17,KAKAMEGA,116437.61,5789.00,110648.61,116437.61,0.00,0.0,0.00
17,18,KERICHO,19742.00,15586.00,4801.00,20387.00,645.00,0.0,0.00
18,19,KIAMBU RD,602965.90,216182.01,386738.89,602920.90,-45.00,0.0,0.00

In [658]:
# ✅ Step 1: Filter newaspire where Amount_check is 'False'
aspire_recs_data = newaspire[
    newaspire['Amount_check'].astype(str).str.strip().str.lower() == 'false'
]

# ✅ Step 2: Ensure AMOUNT is numeric
aspire_recs_data['AMOUNT'] = pd.to_numeric(aspire_recs_data['AMOUNT'], errors='coerce')

# ✅ Step 3: Drop rows with NaN in AMOUNT before summing
aspire_recs_data = aspire_recs_data.dropna(subset=['AMOUNT'])

# ✅ Step 4: Group by STORE_NAME and sum AMOUNT
aspire_recs_grouped = aspire_recs_data.groupby('STORE_NAME')['AMOUNT'].sum().reset_index()
aspire_recs_grouped.columns = ['STORE_NAME', 'Asp_Recs']

# ✅ Step 5: Drop old Asp_Recs if exists
if 'Asp_Recs' in card_summary.columns:
    card_summary.drop(columns=['Asp_Recs'], inplace=True)

# ✅ Step 6: Merge into card_summary
card_summary = card_summary.merge(aspire_recs_grouped, on='STORE_NAME', how='left')
card_summary['Asp_Recs'] = card_summary['Asp_Recs'].fillna(0)

# ✅ Step 7: Remove old TOTAL row
card_summary = card_summary[card_summary['STORE_NAME'] != 'TOTAL']

# ✅ Step 8: Recalculate TOTAL row including Asp_Recs
numeric_cols = ['Aspire_Zed', 'kcb_paid', 'equity_paid', 'Gross_Banking',
                'Variance', 'kcb_recs', 'Equity_recs', 'Asp_Recs']

card_summary[numeric_cols] = card_summary[numeric_cols].apply(pd.to_numeric, errors='coerce')
totals = card_summary[numeric_cols].sum()

# ✅ Step 9: Build TOTAL row
total_row = pd.DataFrame([{
    'No': '',
    'STORE_NAME': 'TOTAL',
    'Aspire_Zed': totals['Aspire_Zed'],
    'kcb_paid': totals['kcb_paid'],
    'equity_paid': totals['equity_paid'],
    'Gross_Banking': totals['Gross_Banking'],
    'Variance': totals['Variance'],
    'kcb_recs': totals['kcb_recs'],
    'Equity_recs': totals['Equity_recs'],
    'Asp_Recs': totals['Asp_Recs']
}])

# ✅ Step 10: Append total row
card_summary = pd.concat([card_summary, total_row], ignore_index=True)

# ✅ Step 11: Display final result
display(card_summary.tail())

<ipython-input-658-388308107>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aspire_recs_data['AMOUNT'] = pd.to_numeric(aspire_recs_data['AMOUNT'], errors='coerce')

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking,Variance,kcb_recs,Equity_recs,Asp_Recs
57,58,UTAWALA EXPRESS,138961.38,31554.45,107993.93,139548.38,587.00,0.0,587.00,0.0
58,59,UTAWALA MAIN,131389.36,18024.58,113239.78,131264.36,-125.00,0.0,0.00,0.0
59,60,WAIYAKI WAY,318333.07,54599.60,283733.47,338333.07,20000.00,20000.0,0.00,0.0
60,61,WESTLANDS,259006.94,33235.28,225970.66,259205.94,199.00,0.0,199.00,0.0
61,,TOTAL,11640052.65,3291999.79,8402623.89,11694623.68,54571.03,37917.0,28998.03,12249.0

In [659]:
# Step 1: Remove old TOTAL row if it exists
card_summary = card_summary[card_summary['STORE_NAME'] != 'TOTAL']

# Step 2: Define all numeric columns to sum (including new ones)
numeric_cols = ['Aspire_Zed', 'kcb_paid', 'equity_paid', 'Gross_Banking', 'Variance', 'kcb_recs', 'Equity_recs', 'Asp_Recs']

# Step 3: Calculate totals
totals = card_summary[numeric_cols].sum()

# Step 4: Create TOTAL row using all columns in card_summary (including No and STORE_NAME)
total_row = pd.DataFrame([{
    'No': '',
    'STORE_NAME': 'TOTAL',
    'Aspire_Zed': totals.get('Aspire_Zed', 0),
    'kcb_paid': totals.get('kcb_paid', 0),
    'equity_paid': totals.get('equity_paid', 0),
    'Gross_Banking': totals.get('Gross_Banking', 0),
    'Variance': totals.get('Variance', 0),
    'kcb_recs': totals.get('kcb_recs', 0),
    'Equity_recs': totals.get('Equity_recs', 0),
    'Asp_Recs': totals.get('Asp_Recs', 0)
}])

# Step 5: Append total row
card_summary = pd.concat([card_summary, total_row], ignore_index=True)

# Step 6: Display final result
display(card_summary.tail())

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking,Variance,kcb_recs,Equity_recs,Asp_Recs
57,58,UTAWALA EXPRESS,138961.38,31554.45,107993.93,139548.38,587.00,0.0,587.00,0.0
58,59,UTAWALA MAIN,131389.36,18024.58,113239.78,131264.36,-125.00,0.0,0.00,0.0
59,60,WAIYAKI WAY,318333.07,54599.60,283733.47,338333.07,20000.00,20000.0,0.00,0.0
60,61,WESTLANDS,259006.94,33235.28,225970.66,259205.94,199.00,0.0,199.00,0.0
61,,TOTAL,11640052.65,3291999.79,8402623.89,11694623.68,54571.03,37917.0,28998.03,12249.0

In [660]:
# Ensure missing columns default to 0 before calculating
for col in ['Variance', 'kcb_recs', 'Equity_recs', 'Asp_Recs']:
    if col not in card_summary.columns:
        card_summary[col] = 0

# Compute Net_variance
card_summary['Net_variance'] = (
    card_summary['Variance']
    - card_summary['kcb_recs']
    - card_summary['Equity_recs']
    + card_summary['Asp_Recs']
)

# Display result
display(card_summary.tail())

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking,Variance,kcb_recs,Equity_recs,Asp_Recs,Net_variance
57,58,UTAWALA EXPRESS,138961.38,31554.45,107993.93,139548.38,587.00,0.0,587.00,0.0,0.0
58,59,UTAWALA MAIN,131389.36,18024.58,113239.78,131264.36,-125.00,0.0,0.00,0.0,-125.0
59,60,WAIYAKI WAY,318333.07,54599.60,283733.47,338333.07,20000.00,20000.0,0.00,0.0,0.0
60,61,WESTLANDS,259006.94,33235.28,225970.66,259205.94,199.00,0.0,199.00,0.0,0.0
61,,TOTAL,11640052.65,3291999.79,8402623.89,11694623.68,54571.03,37917.0,28998.03,12249.0,-95.0

In [661]:
!pip install xlsxwriter

import pandas as pd

# --- COLAB ONLY: Enable download ---
from google.colab import files

# ------------------ Prepare Sheets ------------------

aspire_recs_data = newaspire[newaspire['Amount_check'] == 'False'].copy()

equity_recs_data = newmerged_cards[
    (newmerged_cards['Source'].str.upper() == 'EQUITY') &
    (newmerged_cards['Amount_check'] == 'False')
].copy()

kcb_recs_data = newmerged_cards[
    (newmerged_cards['Source'].str.upper() == 'KCB') &
    (newmerged_cards['Amount_check'] == 'False')
].copy()

merged_cards['Card_Number'] = merged_cards['Card_Number'].astype(str)
merged_cards['card_check'] = merged_cards['Card_Number'].str[:4] + merged_cards['Card_Number'].str[-4:]
if 'Source' in merged_cards.columns:
    cols = merged_cards.columns.tolist()
    if 'card_check' in cols:
        cols.remove('card_check')
    source_index = cols.index('Source') + 1
    cols.insert(source_index, 'card_check')
    merged_cards = merged_cards[cols]
merged_cards = merged_cards.drop_duplicates()
merged_cards = merged_cards[merged_cards['TID'].notna() & (merged_cards['TID'].astype(str).str.strip() != '')]

aspire['AMOUNT'] = pd.to_numeric(aspire['AMOUNT'], errors='coerce')
aspire['val_check'] = aspire['AMOUNT'] - aspire['rrn_check']
cols = list(aspire.columns)
rrn_idx = cols.index('rrn_check')
new_order = cols[:rrn_idx + 1] + ['val_check'] + cols[rrn_idx + 1:-1] + [cols[-1]]
aspire = aspire[new_order]
aspire = aspire.loc[:, ~aspire.columns.duplicated()]

# ------------------ Add TOTAL to card_summary ------------------

card_summary = card_summary[card_summary['STORE_NAME'] != 'TOTAL']

all_possible = ['Aspire_Zed', 'kcb_paid', 'equity_paid', 'Gross_Banking',
                'Variance', 'kcb_recs', 'Equity_recs', 'Asp_Recs']
numeric_cols = [col for col in all_possible if col in card_summary.columns]

totals = card_summary[numeric_cols].sum()

total_row = {'No': '', 'STORE_NAME': 'TOTAL'}
for col in numeric_cols:
    total_row[col] = totals[col]

card_summary = pd.concat([card_summary, pd.DataFrame([total_row])], ignore_index=True)

# ------------------ Export to Excel Workbook ------------------

filename = "Reconciliation_Report.xlsx"

with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
    card_summary.to_excel(writer, sheet_name='card_summary', index=False)
    aspire_recs_data.to_excel(writer, sheet_name='Asp_Recs', index=False)
    equity_recs_data.to_excel(writer, sheet_name='Equity_recs', index=False)
    kcb_recs_data.to_excel(writer, sheet_name='kcb_recs', index=False)
    merged_cards.to_excel(writer, sheet_name='merged_cards', index=False)
    aspire.to_excel(writer, sheet_name='aspire', index=False)

print("✅ All reports exported successfully to:", filename)

# ------------------ Auto-Download in Colab ------------------

files.download(filename)

Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.11/dist-packages (3.2.3)
✅ All reports exported successfully to: Reconciliation_Report.xlsx

In [662]:
!pip install xlsxwriter

import pandas as pd

# ------------------ Prepare Sheets ------------------

# Asp_Recs (Sheet 2)
aspire_recs_data = newaspire[newaspire['Amount_check'] == 'False'].copy()

# Equity_recs (Sheet 3)
equity_recs_data = newmerged_cards[
    (newmerged_cards['Source'].str.upper() == 'EQUITY') &
    (newmerged_cards['Amount_check'] == 'False')
].copy()

# KCB_recs (New Sheet)
kcb_recs_data = newmerged_cards[
    (newmerged_cards['Source'].str.upper() == 'KCB') &
    (newmerged_cards['Amount_check'] == 'False')
].copy()

# Clean merged_cards (Sheet 5)
merged_cards['Card_Number'] = merged_cards['Card_Number'].astype(str)
merged_cards['card_check'] = merged_cards['Card_Number'].str[:4] + merged_cards['Card_Number'].str[-4:]
if 'Source' in merged_cards.columns:
    cols = merged_cards.columns.tolist()
    if 'card_check' in cols:
        cols.remove('card_check')
    source_index = cols.index('Source') + 1
    cols.insert(source_index, 'card_check')
    merged_cards = merged_cards[cols]
merged_cards = merged_cards.drop_duplicates()
merged_cards = merged_cards[merged_cards['TID'].notna() & (merged_cards['TID'].astype(str).str.strip() != '')]

# Clean aspire (Sheet 6)
aspire['AMOUNT'] = pd.to_numeric(aspire['AMOUNT'], errors='coerce')
aspire['val_check'] = aspire['AMOUNT'] - aspire['rrn_check']
cols = list(aspire.columns)
rrn_idx = cols.index('rrn_check')
new_order = cols[:rrn_idx + 1] + ['val_check'] + cols[rrn_idx + 1:-1] + [cols[-1]]
aspire = aspire[new_order]
aspire = aspire.loc[:, ~aspire.columns.duplicated()]

# ------------------ Recalculate Total Row ------------------

# Remove old TOTAL row
card_summary = card_summary[card_summary['STORE_NAME'] != 'TOTAL']

# Numeric columns to total
numeric_cols = ['Aspire_Zed', 'kcb_paid', 'equity_paid', 'Gross_Banking',
                'Variance', 'kcb_recs', 'Equity_recs', 'Asp_Recs']
totals = card_summary[numeric_cols].sum()

# Create TOTAL row
total_row = pd.DataFrame([{
    'No': '',
    'STORE_NAME': 'TOTAL',
    'Aspire_Zed': totals.get('Aspire_Zed', 0),
    'kcb_paid': totals.get('kcb_paid', 0),
    'equity_paid': totals.get('equity_paid', 0),
    'Gross_Banking': totals.get('Gross_Banking', 0),
    'Variance': totals.get('Variance', 0),
    'kcb_recs': totals.get('kcb_recs', 0),
    'Equity_recs': totals.get('Equity_recs', 0),
    'Asp_Recs': totals.get('Asp_Recs', 0)
}])

# Append to card_summary
card_summary = pd.concat([card_summary, total_row], ignore_index=True)

# ------------------ Export to Excel ------------------

with pd.ExcelWriter("Reconciliation_Report.xlsx", engine='xlsxwriter') as writer:
    card_summary.to_excel(writer, sheet_name='card_summary', index=False)
    aspire_recs_data.to_excel(writer, sheet_name='Asp_Recs', index=False)
    equity_recs_data.to_excel(writer, sheet_name='Equity_recs', index=False)
    kcb_recs_data.to_excel(writer, sheet_name='kcb_recs', index=False)
    merged_cards.to_excel(writer, sheet_name='merged_cards', index=False)
    aspire.to_excel(writer, sheet_name='aspire', index=False)

print("✅ All sheets exported to 'Reconciliation_Report.xlsx'")

Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.11/dist-packages (3.2.3)
✅ All sheets exported to 'Reconciliation_Report.xlsx'

In [663]:
# Temporarily remove row display limit
pd.set_option('display.max_rows', None)

# Display full DataFrame
display(card_summary)

# (Optional) Reset display limit afterward
# pd.reset_option('display.max_rows')

,No,STORE_NAME,Aspire_Zed,kcb_paid,equity_paid,Gross_Banking,Variance,kcb_recs,Equity_recs,Asp_Recs,Net_variance
0,1,BANDARI,184796.51,18492.01,171304.50,189796.51,5000.00,5000.0,0.00,0.0,0.000000e+00
1,2,BURUBURU,167622.86,0.00,167622.86,167622.86,0.00,0.0,0.00,0.0,0.000000e+00
2,3,CHAKA RD,237663.93,146374.84,95205.54,241580.38,3916.45,0.0,3916.45,0.0,1.182343e-11
3,4,CHANIA,337269.39,80762.36,256507.03,337269.39,0.00,0.0,0.00,0.0,0.000000e+00
4,5,CROSSROADS-KAREN,103460.80,0.00,100360.80,100360.80,-3100.00,0.0,941.00,4041.0,0.000000e+00
5,6,DONHOLM,111860.50,56317.05,55543.45,111860.50,0.00,0.0,0.00,0.0,0.000000e+00
6,7,EASTERN BYPASS 1,160548.77,124415.44,36847.33,161262.77,714.00,0.0,714.00,0.0,0.000000e+00
7,8,EASTERN BYPASS 2,193582.67,28021.47,165561.20,193582.67,0.00,0.0,0.00,0.0,0.000000e+00
8,9,ELDOCENTER,96255.78,14339.05,81916.73,96255.78,0.00,0.0,0.00,0.0,0.000000e+00
9,10,EMBAKASI,381095.77,105676.68,275449.09,381125.77,30.00,0.0,0.00,0.0,3.000000e+01
10,11,FEDHA,256301.37,33586.25,222715.12,256301.37,0.00,0.0,0.00,0.0,0.000000e+00
11,12,HIGHWAY-MLOLONGO,111618.44,12805.15,99552.29,112357.44,739.00,739.0,0.00,0.0,0.000000e+00
12,13,JIPANGE,312616.38,94592.06,218024.32,312616.38,0.00,0.0,0.00,0.0,0.000000e+00
13,14,JOSKA,167188.39,129020.37,38168.02,167188.39,0.00,0.0,0.00,0.0,0.000000e+00
14,15,KAHAWA SUKARI,97730.52,36872.97,60205.55,97078.52,-652.00,0.0,0.00,652.0,0.000000e+00
15,16,KAHAWA WEST,214501.11,141162.37,73338.74,214501.11,0.00,0.0,0.00,0.0,0.000000e+00
16,17,KAKAMEGA,116437.61,5789.00,110648.61,116437.61,0.00,0.0,0.00,0.0,0.000000e+00
17,18,KERICHO,19742.00,15586.00,4801.00,20387.00,645.00,0.0,0.00,0.0,6.450000e+02
18,19,KIAMBU RD,602965.90,216182.01,386738.89,602920.90,-45.00,0.0,0.00,45.0,0.000000e+00
19,20,KIKUYU RD,46716.09,0.00,46716.09,46716.09,0.00,0.0,0.00,0.0,0.000000e+00
20,21,KILELESHWA,761710.11,360878.27,400831.84,761710.11,0.00,0.0,0.00,0.0,0.000000e+00
21,22,KILIMANI,555915.85,83375.30,473120.55,556495.85,580.00,580.0,0.00,0.0,0.000000e+00
22,23,KISERIAN,263623.20,145905.44,116010.76,261916.20,-1707.00,-1707.0,0.00,0.0,0.000000e+00
23,24,KISII,242034.64,0.00,242034.64,242034.64,0.00,0.0,0.00,0.0,0.000000e+00
24,25,KITALE,201507.64,94762.21,106745.43,201507.64,0.00,0.0,0.00,0.0,0.000000e+00
25,26,KITENGELA,328394.37,10566.72,317827.65,328394.37,0.00,0.0,0.00,0.0,0.000000e+00
26,27,KITUI,86860.26,1241.92,85618.34,86860.26,0.00,0.0,0.00,0.0,0.000000e+00
27,28,KONDELE,45581.65,16051.00,29530.65,45581.65,0.00,0.0,0.00,0.0,0.000000e+00
28,29,LAVINGTON,281719.46,1642.00,299674.04,301316.04,19596.58,0.0,19596.58,0.0,-4.365575e-11
29,30,MACHAKOS EXPRESS,28265.53,3394.00,39420.48,42814.48,14548.95,0.0,0.00,0.0,1.454895e+04
30,31,MACHAKOS PIONEER,69501.11,7882.32,47069.84,54952.16,-14548.95,0.0,0.00,0.0,-1.454895e+04
31,32,MAYFAIR,22514.45,2865.00,19649.45,22514.45,0.00,0.0,0.00,0.0,0.000000e+00
32,33,MFANGANO,111283.18,25043.84,86079.34,111123.18,-160.00,0.0,0.00,160.0,0.000000e+00
33,34,MILELE-NGONG,224027.81,95084.21,128943.60,224027.81,0.00,0.0,0.00,0.0,0.000000e+00
34,35,MOMBASA ROAD,149837.67,24769.34,125068.33,149837.67,0.00,0.0,0.00,0.0,0.000000e+00
35,36,MTWAPA EXPRESS,102610.58,50672.20,53677.38,104349.58,1739.00,0.0,1739.00,0.0,0.000000e+00
36,37,MTWAPA MALL,306202.42,172770.27,128443.15,301213.42,-4989.00,0.0,0.00,4989.0,0.000000e+00
37,38,NANYUKI,292775.84,39772.27,253003.57,292775.84,0.00,0.0,0.00,0.0,0.000000e+00
38,39,NAROK MORAN,257857.40,16601.10,241256.30,257857.40,0.00,0.0,0.00,0.0,0.000000e+00
39,40,NYALENDA,42407.89,18417.95,23989.94,42407.89,0.00,0.0,0.00,0.0,0.000000e+00
40,41,NYALI,225064.49,135426.77,89637.72,225064.49,0.00,0.0,0.00,0.0,0.000000e+00
41,42,OGINGA ODINGA,64013.34,7133.94,56879.40,64013.34,0.00,0.0,0.00,0.0,0.000000e+00
42,43,OTC,92372.26,7765.00,84607.26,92372.26,0.00,0.0,0.00,0.0,0.000000e+00
43,44,OUTERING,44058.20,212.00,43846.20,44058.20,0.00,0.0,0.00,0.0,0.000000e+00
44,45,OUTERING 2,173009.47,16371.20,156638.27,173009.47,0.00,0.0,0.00,0.0,0.000000e+00
45,46,PIONEER,144063.23,40590.80,103472.43,144063.23,0.00,0.0,0.00,0.0,0.000000e+00
46,47,PIPELINE,36341.15,12849.95,24796.20,37646.15,1305.00,0.0,1305.00,0.0,0.000000e+00
47,48,RONGAI EXPRESS,51185.81,24610.00,28380.81,52990.81,1805.00,1805.0,0.00,0.0,0.000000e+00
48,49,RONGAI MAIN,251222.76,40745.98,210476.78,251222.76,0.00,0.0,0.00,0.0,0.000000e+00
49,50,ROYSAMBU,110310.93,0.00,110310.93,110310.93,0.00,0.0,0.00,0.0,0.000000e+00
50,51,RUAI,173150.80,72311.26,100839.54,173150.80,0.00,0.0,0.00,0.0,0.000000e+00
51,52,RUAKA,347055.67,62675.71,282017.96,344693.67,-2362.00,0.0,0.00,2362.0,0.000000e+00
52,53,RUIRU,163559.22,79748.27,83810.95,163559.22,0.00,0.0,0.00,0.0,0.000000e+00
53,54,SHABAAB,4800.00,0.00,4155.00,4155.00,-645.00,0.0,0.00,0.0,-6.450000e+02
54,55,T-MALL,204911.73,1598.00,203313.73,204911.73,0.00,0.0,0.00,0.0,0.000000e+00
55,56,THOME,313835.29,153753.86,160081.43,313835.29,0.00,0.0,0.00,0.0,0.000000e+00
56,57,TOM MBOYA,98801.70,67102.70,43199.00,110301.70,11500.00,11500.0,0.00,0.0,0.000000e+00
57,58,UTAWALA EXPRESS,138961.38,31554.45,107993.93,139548.38,587.00,0.0,587.00,0.0,0.000000e+00
58,59,UTAWALA MAIN,131389.36,18024.58,113239.78,131264.36,-125.00,0.0,0.00,0.0,-1.250000e+02
59,60,WAIYAKI WAY,318333.07,54599.60,283733.47,338333.07,20000.00,20000.0,0.00,0.0,0.000000e+00
60,61,WESTLANDS,259006.94,33235.28,225970.66,259205.94,199.00,0.0,199.00,0.0,0.000000e+00
61,,TOTAL,11640052.65,3291999.79,8402623.89,11694623.68,54571.03,37917.0,28998.03,12249.0,NaN